redis/redis-doc

- topics/faq.md
The "Understanding Virtual Memory" article cited when motivating the setting for overcommit_memory had the meaning of
the values 1 and 2 reversed. I found it while reading this comment http://superuser.com/a/200504.
With this commit, I'm trying to make this known to the Redis FAQ reader. The proc(5) man page has it pretty clear:
/proc/sys/vm/overcommit_memory
This file contains the kernel virtual memory accounting mode.
Values are:
0: heuristic overcommit (this is the default)
1: always overcommit, never check
2: always check, never overcommit
In mode 0, calls of mmap(2) with MAP_NORESERVE are not
checked, and the default check is very weak, leading to the
risk of getting a process "OOM-killed".  Under Linux 2.4 any
nonzero value implies mode 1.  In mode 2 (available since
Linux 2.6), the …
> Fix vm.overcommit faq

- topics/faq.md
Since Hashes are using dict they can also have a max of ~2^32 fields.
> Add Hash to question about max number of elements

- clients.json
Please accept this PR since Java redis client lettuce has a new maintainer. This change reflects the new path to the repository.
> Update client.json with new maintained lettuce repo path

- clients.json
Redox is a modern, asynchronous, and fast C++11 client for Redis. It's new, but I think the API has a lot of promise and the performance is great. Can you add it?
Thanks,
Hayk
> Add redox to C++ clients in clients.json

- commands/script exists.md
The example doesn't work and returns two errors.
> `SCRIPT` isn't allowed by web-embedded Redis

- topics/data-types-intro.md
Changes 'intersection' to 'union' where appropriate in topics/data-types-intro.
> Fix 2 typos in data-types-intro

- topics/sentinel.md
I believe the intended text was 'there are 3 nodes' not 'there are there nodes'
> sentinel.md typo fix

- clients.json
redis-rs is currently the only library that works with any recent rust version or is maintained.
> Recommend redis-rs and reorder the rust libraries.

- clients.json
The former description was not valid anymore, as we have removed dependency on hiredis by creating two packages: a RESP encoder/decoder and a Redis client library that uses the RESP encoder/decoder.
> Updating description for the gosexy/redis package.

- clients.json
I've completed a new C++ redis client, which support all redis commands including redis3.0 cluster. There're 12 C++ classes for 12 redis structur types, and 150+ functions for all redis commands. The redis client also supports connection pool and cluster pool.
The C++ HEADER in https://github.com/zhengshuxin/acl/tree/master/lib_acl_cpp/include/acl_cpp/redis
The samples in https://github.com/zhengshuxin/acl/tree/master/lib_acl_cpp/samples/redis
The redis cluster sample in https://github.com/zhengshuxin/acl/blob/master/lib_acl_cpp/samples/redis/redis_cluster/redis_cluster.cpp
The redis client source codes in https://github.com/zhengshuxin/acl/tree/master/lib_acl_cpp/src/redis
The samples are below:
1)  simple example for redis string:
void test_redis_string(acl::redis_string& cmd, const …
> A new C++ redis client, support all redis commands including redis3.0 cluster

- clients.json
- topics/cluster-tutorial.md
So update description and add to cluster-tutorial...
Benckmark in single node:
> thunk-redis support redis cluster

- clients.json
ioredis is a robust, full-featured Redis client used in the world's biggest online commerce company Alibaba. It supports Cluster, Sentinel, Pipelining and Lua Scripting.
Note that I add "recommended" flag to it(disclaimer: I am the author of ioredis) for the following reasons:
1. The current recommended client [node_redis](https://github.com/mranney/node_redis) is not active any more and it has some non-trivial bugs unfixed and many issues unresolved(see [issues on node_redis](https://github.com/mranney/node_redis/issues?q=is%3Aopen+is%3Aissue) and [Motivation](https://github.com/luin/ioredis#motivation)).
2. ioredis has already been used in the production environment in our company. It works very well and turns out to be faster and more robust than node_redis.
3. ioredis is the only …
> Add ioredis client

- commands/expire.md
Here is a small typo fix in Expire command description
> fix typo in how Redis expires keys section

- commands/cluster setslot.md
1. Just a typo, it should be the destination id as in the docu above
2. Isn't the correct and better way to use `SETSLOT id NODE node-id` on one node and let it propagate? `redis-trib.rb` does the same.
> Setslot fixes

- commands/eval.md
There was a missing trailing `"` in one of the cmsgpack EVAL examples. Simply added it
> Fix typo in cmsgpack eval example

- commands.json
Current documentation states that ZADD takes NX|XX|CH|INCR, but those
flags can be composed.
> ZADD allows multiple flags

- tools.json
RedisKeychain is a Node.js library for streamlining the configuration and maintenance of your Redis namespace.
* template engine for key names;
* expiry configuration utility;
* key-to-client binding.
[More info](https://github.com/adriano-di-giovanni/node-redis-keychain)
> Add entry for RedisKeychain to tools.json

- topics/partitioning.md
> Now that we've got Redis Cluster, Twemproxy is not necessary anymore

- commands/keys.md
Specifically the character set's complement and range.
A separate pattern-matching.md topic that's linked from `KEYS` and `[HSZ]?SCAN` doc pages seems to be a good idea <- thoughts?
> Added missing glob-style patterns

- clients.json
Haxe was renamed. From "haXe" to "Haxe".
See [official website](http://haxe.org/).
> Haxe was renamed

- clients.json
Moving the package out of the company namespace and into my personal one to ensure continued support.
> Move package to new vendor namespace

- topics/cluster-tutorial.md
The output of command shows  **114** lost but the description is **144**.
> Make the number consistent with command output

- clients.json
I added [Redix](https://github.com/whatyouhide/redix), a Redis client I developed in pure Elixir, to the list of clients in `clients.json`. Let me know if I can do anything else, thanks! :)
> Add the Redix client

- topics/distlock.md
The current link to the PHP implementation has some limitations, i.e. there's no release, it doesn't support both Redis-APIs. So therefore I [implemented the Redlock algorithm](https://github.com/malkusch/lock#phpredismutex) as well and released it. I would be happy to see that reference in the documentation.
Also I'd like to use this opportunity to ask why the algorithm proposes to release also locks which weren't acquired.
> Further PHP implementation

- clients.json
Hi,
I've developed a C++11 redis client based on boost::asio.
Library is tested and documented (more documentation is coming).
I've added references to this library in the clients.json file.
> add cpp_redis to clients.json

- tools.json
[Hedis Website](http://hedis.io/)
Traditionally, application server retrieves hot data from in-memory database (like Redis) to reduce unnecessary paths. If in-memory database doesn't have specific data, application server gets back to retrieve data from original database.
Hedis can retrieve data from ANY database directly via Redis. Application server retrieves hot data from Hedis server, If Hedis server doesn't have specific data, Hedis retrieves data from original database via ANY connector.
> Add Hedis support

- clients.json
As of the latest release, it only provides TCP, HTTP, and UDP protocol implementations.
> Remove Aleph from client implementation list

- commands.json
- commands/cluster-nodes.md
- commands/cluster-setslot.md
- commands/hincrbyfloat.md
- commands/scan.md
- topics/pubsub.md
- topics/security.md
- topics/twitter-clone.md
Replaces instances of "an hash" with "a hash".
> Corrects a typo

- commands/eval.md
While using a semicolon after each statement is legit in Lua, it isn't needed nor customary.
> Removes semicolon from Lua code

- clients.json
Definition of "active" is taken from http://redis.io/clients
(activity on the official repository within the latest 6 months)
> Remove flag "active" to some inactive clients

- clients.json
These libraries are no longer maintained. They all have no new commits in over 2 years.
> Remove outdated PHP libraries

- commands/object.md
Actually Redis do not use zipmap. Ziplist used as small hash encoding. This pull request fix this in `object ecnding` command description.
> Fix hash encoding in object encoding command

- topics/quickstart.md
The quickstart document was missing the "sudo" command required to run /etc/init.d/redis_6379 start
> Added "sudo" to the "/etc/init.d/redis_6379 start" command in quickstart

- clients.json
I had to change the library name due to Swift name conventions.
> Change Swift-Redis client name to ZRedis

- commands/migrate.md
> Fix typo: preset -> present

- topics/sentinel.md
In sentinel doc, "Example 3: Sentinel in the client boxes" section,  it seems the second **master** should be replaced with **slave**.
> so the master can't stop accepting queries when is disconnected by its **master**,
otherwise the master would never be available during slave failures.
> Fix typo, change master to slave

- topics/lru-cache.md
**allkeys-lru** is not suitable for both caching and to have a set of persistent keys in one instance. But **volatile-lru** is very suitable for the situation. 
This is just my point of view, please check it. Very thanks.
> fix lru-cache.md: allkeys-lru is not suitable for persistent situation

- topics/admin.md
changed `topic/quickstart` to `topics/quickstart` to fix the broken link on the website
> fix typo link topics/quickstart

- clients.json
r3c is a Redis Cluster C++ Client, based on hiredis and support standalone, it's easy to make and use, not depends on C++11 or later.
> add r3c, a Redis Cluster C++ Client

- tools.json
We've been successfully using this library in production for 6 months and would like to share with the community. I just added support for parsing RDB version 7.
> Add Java rdb-parser tool

- topics/indexes.md
075 and 200
0            2
7            0
5            0
027050 not 027005
Also there:
001[00]1011 - 9 bit
011[00]1000 - 9 bit
should be four zeroes and 18 bit result, no? 0001110011[0000]1010
> Small error in example

- clients.json
It moved out of the standard library, thus there's no more docs on the official website.
> Updated Nim client info

- commands/expire.md
- commands/shutdown.md
- topics/internals-vm.md
- topics/replication.md
In English language there is no 'think at' phrase. Also fixed a typo.
> Change 'think at' phrases to proper ones

- commands/georadius.md
Georadius: changed the word "fairest" to "farthest" because "fairest" is the wrong word and it doesn't make sense in this context. The word "fairest" has nothing to do with distance.
> changed the word "fairest" to "farthest" in georadius

- topics/cluster-tutorial.md
I think this is correct, although I can't get the `consistency-test.rb` script to output what it lost.
> I think this is what it is suppossed to be.

- commands.json
I don't quite understand the original phrasing but think this fixes a typo and hope that it correctly describes the behavior of `PFCOUNT`.
> Fix typo in PFCOUNT time complexity description

- tools.json
As the title.
We and some other companies used this tool in the production for redis migration.
> add 'redis-migrate-tool' for redis tools

- commands/srandmember.md
The word `bucked` should be `bucket`.
> fix typo in commands/srandmember.md

- commands/expire.md
- commands/expireat.md
- topics/notifications.md
The current documentation for EXPIRE does not mention that specifying a timeout less than or equal to zero does actually perform a DEL. This PR fixes this issue.
Also see http://stackoverflow.com/q/40636291/2516943
English is not my native language, so feel free to rephrase.
> Mention EXPIRE behavior with non-positive timeouts

- topics/introduction.md
This sounds much better with an 'a' between "used as" and "database". Fixes
the grammar, which I noticed whilst reading redis.io.
> Fix grammar

- clients.json
The https://github.com/Livestream/scredis is apparently no longer maintained, but links to a new repository: https://github.com/scredis/scredis.
> Updated link to scredis repo

- topics/data-types-intro.md
Fixed typo in: `data-types-intro` documentation.
> Fixed typo in data-types-intro documentation

- topics/quickstart.md
System timer isn't relevant / needed since Ruby 1.9.
> Remove outdated references in quickstart example

- topics/ARM.md
The added commas make it more clear the performance difference between Pi 3 and Pi 1/B. I had to look a few times to see that Test 1 was x10+ on the pi3 because it was just zeros.
> Added commas in ops/sec

- topics/distlock.md
I've been working on a distributed lock manager for asynchronous python (with asyncio).
This module can help other people who use asyncio with redis. I searched for something similar before starting and I couldn't find anything.
> Added asyncio python implementation to distlock implementation list

- topics/sentinel.md
Should explain in the "Sentinel and Redis authentication" how to set up
Sentinels so that they can connect to Redis servers that use
authentication.
/cc @badboy
> Add detail about `sentinel auth-pass` directive

- commands/sort.md
Small change to SORT documentation reply type specifying that it can either be an array or integer.
> Sort returns different replies depending on command arguments.

- topics/data-types-intro.md
@antirez I guess the sentence is referring to `values` and not `keys`.
> Fixed typo in data-types-intro.md

- commands/expire.md
- commands/expireat.md
- commands/pexpire.md
- commands/pexpireat.md
The documentation wasn't clear about why a timeout might not be set for expiry commands, so I had to dig into the source code to find the answer.
In the [latest version of the EXPIRE source code](https://github.com/antirez/redis/blob/3.0.7/src/db.c#L875-L923) it only returns 0 if the key doesn't exist.
Before 2.2.0, commit https://github.com/antirez/redis/commit/0cf5b7b57cde8b699198a866b04feca9f5394d03 removed the possibility of expire returning 0 because expire couldn't be set.  Before that commit, the expiry couldn't be set for a key that already had its expiry set.  
I clarified the reason for EXPIRE returning 0 to mention that it happened when the timeout was already set under the [EXPIRE section on redis prior to 2.1.3](http://redis.io/commands/expire#differences-in-redis-prior-213), …
> Expire only returns 0 if the key doesn't exist.

- topics/lru-cache.md
Fixed misspelled hint of using "allkeys-lru" in having both cache and storage keys in single Redis instance. It should be "volatile-lru" instead.
> volatile-lru instead of allkeys-lru in lru-cache topic

- topics/lru-cache.md
Also make the statements more consistents among one another.
> Fix grammar in documentation for eviction polices.

- commands/command.md
- topics/ARM.md
- topics/indexes.md
- topics/rediscli.md
- topics/replication.md
- topics/twitter-clone.md
No edits for style, just typos.
> Copy edits for typos/misspellings

- tools.json
facil.io includes an asynchronous Redis client as well as a RESP
parser/formatter that could be used as an independent module.
The parser and client were written from the ground up and are licensed
under the MIT license.
This places fail.io in a unique position, the could provide an MIT
licensing option where required. This is in contrast to most of the
other clients, that are based on hiredis and require the BSD-3-clause
license.
This might not be the fastest client or parser (it's more concerned with
protecting itself from bad code than with being optimized), but it is
(to the best of my knowledge) the only MIT licensed option.
Thanks! 👍🏻
===
Iodine is a Ruby HTTP / Websocket server with native Pub/Sub (built
using the facil.io C framework).
Iodine includes an integrated Redis client …
> Consolidate PR #836 and #837 into an updated branch

- topics/config.md
https://redis.io/topics/config needs some link love for v4, this adds that and normalizes the periods on the end of the lines.
> Add Redis 3.2 and 4.0 config links to config docs

- clients.json
changed acl-redis library's link:
https://github.com/acl-dev/acl/tree/master/lib_acl_cpp/samples/redis
https://github.com/acl-dev/acl/tree/master/lib_acl_cpp/include/acl_cpp/redis
> changed acl-redis library's link

- clients.json
https://github.com/vert-x/mod-redis is deprecated.
> Update Vert.X client repository.

- topics/pubsub.md
It's pretty frustrating to follow the docs, type in UNSUBSCRIBE and see nothing in redis-cli. See https://stackoverflow.com/questions/17621371/redis-unsubscribe
> Make clear that redis-cli won't UNSUBSCRIBE

- topics/data-types-intro.md
`no elements into the list` -> `no elements in the list`
> Fix a Small Typo

- commands/object.md
Remove leading spaces from the documentation for `OBJECT FREQ` and
`OBJECT HELP`.
These were previously in a nested `<ul>` so were indented twice in the
HTML rendered docs, and also broke the `rake format` task:
```
formatting commands/object.md...rake aborted!
don't know what to do for inline node ul
```
> Fix formatting in OBJECT documentation

- commands.json
- commands/info.md
- commands/memory-doctor.md
- commands/memory-help.md
- commands/memory-malloc-stats.md
- commands/memory-purge.md
- commands/memory-stats.md
- commands/memory-usage.md
A stab a documenting v4's `MEMORY` command /cc @antirez 
Additionally, as part of this effort it would be good to update `INFO`'s page - ~currently marked as a WIP commit~ requires an expert review for correctness.
TODO:
1. Use this opportunity to document active defragmentation as well 
Additional ponderings:
1. Is 'server' the right group or is a new one needed
2. Should 'memory help' be documented (ATM yes), but also applies to 'debug help' etc
3. Speaking of debug, there's quite a few subcommands missing from the docs. Should they be documented? They're temporary but temporary things tend to last forever...
4. I see that that redis/unstable has 'memory doctor' in the help, whereas 4.0 doesn't although it is supported by the server - is that intentional or an omission (i.e. PR to …
> Documents the `MEMORY` command

- commands.json
Fixes #943 
- Needs analysis for time "complexity" entries
- Summaries need reviewed, and XCLAIM summary needs added
> Add XINFO, XGROUP, XACK, XTRIM, XCLAIM, and XDEL to commands.json

- commands/xpending.md
first line reads consumer name, when i think you mean consumer group name :)
> XPENDING - missing word 'group'

- topics/modules-intro.md
In chapter "Arity and type checks", there is a mistake: 
```
To create a new key, open it for writing and then write to it using one of the key writing functions. Example:
RedisModuleKey *key;
// I think here should be REDISMODULE_WRITE for create new key
key = RedisModule_OpenKey(ctx,argv[1],REDISMODULE_READ);
if (RedisModule_KeyType(key) == REDISMODULE_KEYTYPE_EMPTY) {
RedisModule_StringSet(key,argv[2]);
}
```
Looking forward to your reply. D#-#
Signed-off-by: charpty <charpty@gmail.com>
> Redis modules introduce: fix typo in "creating new keys" example

- commands/xclaim.md
See antirez/redis#5194 for discussion on `JUSTID` semantics. Goes hand in hand with antirez/redis#5907 which embodies this logic.
> Clarify that JUSTID option doesn't increment delivery count

- topics/cluster-spec.md
Fixes #849
https://github.com/antirez/redis/issues/5118
> Clarify that keys must belong to the same slot when performing multi-key operations

- modules.json
`redis-rating` is a Redis module for estimating actual rating from positive/negative ratings.
> add redis-rating to modules.json

- topics/pipelining.md
Came across an issue in the Pipelining appendix question.
> Fix typo/grammar issue in appendix

- topics/signals.md
Document that SIGINT is handled like SIGTERM, as indicated in https://github.com/antirez/redis/blob/8d92885bac17d8d82177a2f51d5b2a03c11ac8fe/src/server.c#L3488
> Document that SIGINT is handled like SIGTERM

- commands/bzpopmin.md
The BZPOPMIN example creates a set named "zset1" but shows the returned value from BZPOPMIN as "zet1".
> Fix typo in BZPOPMIN example

- commands.json
- Documentation was inconsistent in used of `element` and `value` for lists. Normalized  to `element`
- Computational complexity did not account for variadic commands.
> update list command complexity and nomenclature

- commands.json
@antirez & @itamarhaber sorry, I accidentally used "command" instead of "name". Fixed it.
> SET signature containing misleading "expiration"

- clients.json
guile-redis has been updated to support up to redis 5.0 commands.
> clients: added guile-redis

- topics/modules-blocking-ops.md
> Fix typo: "si" -> "is" in topics/modules-blocking-ops

- topics/modules-intro.md
This PR includes following 2 type of fixes
1. Although documents says the example of "INCRBY", but example code uses "INCR"
- Document says following
```
For example if I want to call INCRBY
```
- Actual example code
```
RedisModuleCallReply *reply;
reply = RedisModule_Call(ctx,"INCR","sc",argv[1],"10");
```
2.  Now it includes the unnessary character "se", so this PR remove this.
Finally in order to set the length se use the following call:
-> Finally in order to set the length, use the following call:
> Fix some mistake of modules intro

- topics/faq.md
Hello,
This pull request simply fixes a broken link in the FAQ.
The article is no longer available so let's fix the link to a reworked version of it.
Also, the 1 and 2 values are no longer swapped in this article but let's keep a link to the `proc` man page as it can be useful and simpler than the whole article (here's the [original article](http://web.archive.org/web/20120608085846/http://www.redhat.com/magazine/001nov04/features/vm/) that wrongly explains the 1 and 2 values).
Have a nice day.
> Fix a broken link

- commands/cluster-nodes.md
Fixes missing reference to `cport` value in CLUSTER NODES output as
first introduced by antirez/redis#1c038379f7 and
antirez/redis#b841f3ad1a and released in Redis v4.0.0.
Fixes #983 
@itamarhaber takin' all tha sweet sweet interwebz pointz for mahself mwa ha ha!
> fix(cluster-nodes): include cport reference

- clients.json
After a few years of design and testing, with lots of feedback from
people testing it, I'm ready to say that the newest version of radix is
ready to be used. This version is faster and more flexible, and is
better able to handle new features like streams and RESP3.
Due to go's new module dependency system, this will be the last time the
url of the project needs to change due to a major version change.
> Update project url of the radix go redis client

- topics/distlock.md
https://github.com/hjr265/redsync.go is now deprecated and replaced by https://github.com/go-redsync/redsync.
> Update link to deprecated redsync.go repository

- topics/streams-intro.md
**Consumer group** name is specified as a second parameter. Last parameter is **consumer** name within consumer group
> Fix typo in streams doc

- commands/zadd.md
See: https://github.com/andymccurdy/redis-py/issues/1084
> Clarifies ZADD's return of nil with XX or NX

- clients.json
Add link to RedisPipe - Go's client with implicit pipelining.
Note: I've copied `"recommended": true` mark since there no rules about it, and I personally will recommend it :-)
> Add Go's RedisPipe

- topics/streams-intro.md
"...are server synchronously..." -> "...are served synchronously..."
> Minor typo fix

- commands/msetnx.md
In the example, both the first (successful) and second (unsuccessful) command attempt to set key `key2` to value `there`. It's not obvious from the example that it's the first "there" that's responsible for `key2` having a value of "there", and not the second "there".
This minor change makes it obvious where the value "there" comes from.
> update msetnx example to make it obvious that no partial updates are made

- clients.json
Simon is no longer maintaining cpp_redis. I am maintaining and providing updates for Redis 5 in [this fork](https://github.com/cpp-redis/cpp_redis).
For verification, please view the README at [https://github.com/Cylix/cpp_redis](https://github.com/Cylix/cpp_redis) with a link to my fork.
> Cpp Redis Repository

- topics/transactions.md
I think this "abc" is written by mistake?
> Remove “abc” in the example of transactions

- topics/data-types-intro.md
Not all days have 24 hours, not every hour has 3600 seconds 
Using words avoids spreading the practice of using flat numbers
> Seconds in a day in words

- topics/indexes.md
Mandatory prefix missing, right? 🤷‍♂
> Fix ZRANGEBYLEX syntax

- commands.json
- commands/linsert.md
- commands/lpush.md
- commands/lpushx.md
- commands/lrem.md
- commands/lset.md
- commands/rpush.md
- commands/rpushx.md
Also a small fix to `LREM`'s complexity.
> Uses `element` instead of `value` for lists

- tools.json
Rediseen is a tool helping start REST-like API service for your Redis database, without writing a single line of code.
> Add Rediseen to tools.json

- commands.json
- commands/latency-doctor.md
- commands/latency-graph.md
- commands/latency-help.md
- commands/latency-history.md
- commands/latency-latest.md
- commands/latency-reset.md
- topics/latency-monitor.md
Fixes #821 
This PR includes:
* Minor edits
* Breakdown of latency-monitor.md to subcommand .md files
* Documentation of all event names and their meanings
> Refactors latency-monitoring to subcommands

- commands/pfmerge.md
This surprised me and wasn't a documented behavior, but it is 100% reproducible. The docs state that the source sets are merged into a new HyperLogLog, which set to the destination key; they do not state that the destination key is party to the merge.
```
127.0.0.1:6379> PFADD test 1
(integer) 1
127.0.0.1:6379> PFADD test 2
(integer) 1
127.0.0.1:6379> PFADD test 3
(integer) 1
127.0.0.1:6379> PFCOUNT test
(integer) 3
127.0.0.1:6379> PFADD foo 1
(integer) 1
127.0.0.1:6379> PFADD foo 2
(integer) 1
127.0.0.1:6379> PFCOUNT foo
(integer) 2
127.0.0.1:6379> PFMERGE targ foo test
OK
127.0.0.1:6379> PFCOUNT targ
(integer) 3
127.0.0.1:6379> PFADD bar 6
(integer) 1
127.0.0.1:6379> PFMERGE targ foo bar
OK
127.0.0.1:6379> PFCOUNT targ
(integer) 4
```
> PFMERGE includes target HLL in the merge

- topics/modules-intro.md
The filename references on page https://redis.io/topics/modules-intro were confusing, since it wasn't clear what repo those files were in and those filenames weren't accurate anymore.
This PR makes that clearer by linking to pages themselves and using the same name and order for those pages as on the main Documentation page.
---
A possible future enhancement would be to turn this into a related topics section similar to the related commands section at the top of the [Pub/Sub topic](https://redis.io/topics/pubsub) page or as a sidebar like on the [PUBSUB command](https://redis.io/commands/pubsub) page.
> Reference module documentation pages rather than files from intro page

- commands/eval.md
The section 'Using Lua scripting in RESP3 mode' includes the following sentence:
The RESP3 protocol is semantically more powerful, however most scripts are ok with using just RESP3.
However, the sentence makes no sense. I suspect that it was a typo, which changes the meaning though.
The sentence is probably supposed to go like this:
The RESP3 protocol is semantically more powerful, however most scripts are ok with using just RESP2.
> fix minor error in eval doc

- clients.json
Hi, I would like to have my C++ redis client to be listed in redis-doc. Thanks.
> Adds aedis to the list of C++ redis clients.

- commands.json
arguments for SUBSCRIBE were in the wrong format, which caused this bug: https://github.com/mmkal/handy-redis/issues/46
this change makes them match unsubscribe: https://github.com/antirez/redis-doc/blob/c882f1d3a767a096453489b00d7ec5bcc2eceaa7/commands.json#L2997-L3010
> fix: subscribe should be of type string

- commands/xgroup.md
I'd say this applies to a consumer group not to a consumer.
> add missing word

- commands/monitor.md
Other than admin commands ([1][2]), there are several not logged commands. List them on the same section could be helpful I think.
[1] https://github.com/antirez/redis/commit/d6410ed19a4930895f2591eed224d5ec5449393a
[2] https://github.com/antirez/redis-doc/commit/80129ef3a0fc0e48aeda73f9c9b790cf7bdb2636
> Listing other not logged commands by MONITOR

- tools.json
repo: https://github.com/qishibo/AnotherRedisDesktopManager
desc: 🚀🚀🚀A faster, better and more stable redis desktop manager. What's more, it won't crash when loading a large number of keys.
> add AnotherRedisDesktopManager to tools.json

- topics/data-types.md
Resque repo moved from https://github.com/defunkt/resque to ttps://github.com/resque/resque.
> Fix: Resque repo moved to https://github.com/resque/resque

- topics/client-side-caching.md
1. In section Avoiding race conditions, The arrow direction for describing data flow is wrong and a little bit misleading, this corrects the arrow direction to show the data flow from server to client...
2. fix a typo
> correct the arrow direction in client-side-caching

- commands/acl-genpass.md
> Fix typo in ACL GENPASS command docs

- modules.json
A simple light-weight module to maintain the hash table by common sql users. No any garbage dataset is used. This module could make redis more easy to maintain and learn.
> Add dbx module in list

- commands/xinfo.md
Hi @antirez 
For most markdown renders `<count>` is traded like a HTML tag, thus can't be rendered. What's worse is that some renders think it's not closed so they just yield errors.
> bugfix: <count> is a html tag, should be `<count>`

- commands/acl-genpass.md
Update docs to reflect change in antirez/redis: 639c8a1
> GENPASS uses 256 bits by default, not 128

- commands/client-tracking.md
The correct command for disabling next tracking should use ```CLIENT CACHING no``` rather than off
> change to correct command for disabling tracking in OPTOUT mode

- commands/bgsave.md
Add other reply in the doc.
reference from https://github.com/antirez/redis/blob/fe9acb3469508b1af721d15320b89e2bb2abdd0c/src/rdb.c#L2559
```c
/* BGSAVE [SCHEDULE] */
void bgsaveCommand(client *c) {
int schedule = 0;
/* The SCHEDULE option changes the behavior of BGSAVE when an AOF rewrite
* is in progress. Instead of returning an error a BGSAVE gets scheduled. */
if (c->argc > 1) {
if (c->argc == 2 && !strcasecmp(c->argv[1]->ptr,"schedule")) {
schedule = 1;
} else {
addReply(c,shared.syntaxerr);
return;
}
}
rdbSaveInfo rsi, *rsiptr;
rsiptr = rdbPopulateSaveInfo(&rsi);
if (server.rdb_child_pid != -1) {
addReplyError(c,"Background save already in progress");
} else if (hasActiveChildProcess()) {
if (schedule) {
server.rdb_bgsave_scheduled = 1;
addReplyStatus(c,"Background saving …
```
> Add other reply in the bgsave.md

- commands.json
I want to use commands.json for some type definitions but 3.2 is not a valid semver version.
> fix semver version in commands.json

- topics/acl.md
The number of alphanumeric bytes that are being output by GENPASS in Redis 6.0.0 GA is now 64.
> Fix number of alphanumeric bytes generated by ACL GENPASS

- commands/acl-setuser.md
Remove category typos from ACL SETUSER description.
> Remove typos in ACL SETUSER.

- commands/bitfield.md
This snippet is missing (I think) a `SET` argument.
127.0.0.1:6379> BITFIELD mystring SET i8 #0 100 i8 #1 200
(error) ERR syntax error
127.0.0.1:6379> BITFIELD mystring SET i8 #0 100 SET i8 #1 200
1) (integer) 0
2) (integer) 0
127.0.0.1:6379> get mystring
"d\xc8"
> Correct BITFIELD syntax.

- commands/xinfo.md
- topics/streams-intro.md
Update doc to match `xinfoCommand` in t_stream.c
> Add "last-delivered-id" to XINFO GROUPS

- topics/latency.md
Just found a typo while I was reading.
> Fix typo in latency docs

- topics/data-types.md
Fixes the rendering of this snippet on the website:
> fix: remove faulty cli annotation in data-types.md

- commands.json
Redis 6 support `CLIENT KILL USER username`,  [client-kill.md](https://github.com/antirez/redis-doc/blob/8eb6eb6d632af46c0a05ac01a4af5411252e96ae/commands/client-kill.md#L18) was updated but not with commands.json
> bugfix: add USER option for CLIENT KILL command.

- clients.json
I updated the php-redis-client, now it supports Redis v6.
Could you please merge the PR for updating client's description.
> Update cheprasov/php-redis-client description

- topics/client-side-caching.md
This PR fix two things:
1. use the correct command for enabling client tracking for next keys in opt in mode
2. since noreply was not supported in current version of Redis(not sure whether we need to support it later or not), but in my point of view we should not include this in this documentation in order to avoid confusion for users..
> update tracking doc to make it consistant with implementation

- topics/client-side-caching.md
Since optin mode tracking is already in Redis 6 releases, we may need to remove this note from docs
> remove Work in proress note for optin tracking

- topics/notifications.md
The expire command in keyspace notification has two potential issues: 1. it missed the other related commands,like PEXPIRE. 2. The event generated when giving past time is wrong, should be del rather than expired.
> fix expire command in keyspace event doc

- commands/lpos.md
I believe there is a minor error in the example here, the `element` in `LPOS` command is required. @itamarhaber 
```
127.0.0.1:9998> LPOS mylist COUNT 0
(error) ERR syntax error
```
> bugfix: syntax error in lpos' doc. element is missing.

- commands/config-set.md
Update reference from 2.8/redis.conf to 6.0/redis.conf
> Corrected reference to 6.0 redis.conf

- commands.json
"to serialized it" -> "to serialize it"
> Fix typo/spelling in DUMP documentation

- modules.json
Redis-ImageScout module introduces a native datatype for indexing image fingerprints for  near-duplicate detection.  Robust to slight distortion.
> add Redis-ImageScout module

- tools.json
Itamar Haber invited me to add [Runnel](https://github.com/mjwestcott/runnel), a stream processing framework for Python that adds Kafka-like semantics to the streams data structure. I wrote about this topic in a blog post [comparing Redis streams and Kafka](https://mattwestcott.co.uk/blog/redis-streams-vs-kafka). Thanks!
> Add Runnel to tools.json

- commands/command.md
The OOM (Out Of Memory) meaning is not explained elsewhere in the page
> @haadj explicit the OOM abbreviation

- commands.json
- commands/migrate.md
Regrettably, the current syntax markup doesn't allow for "one out of these subcommands" so that's the best we can do.
After:
Also, formalizes the command's history.
> Adds AUTH2 form to `MIGRATE`

- commands.json
- commands/auth.md
> Adds ACL `AUTH` form syntax

- clients.json
Also marks any Swift client that hasn't received an update in over two years as inactive.
The justification for **RediStack** being the recommended client library is due to being accepted by the [Server-side Swift Working Group](https://github.com/swift-server/sswg/blob/main/proposals/0004-nio-redis.md)
> Update clients.json for Swift language

- wordlist
CJSON was a duplicate inside ./wordlist.
PSYNC is a command inside ./commands.json and therefore should not be
listed in the ./wordlist file again.
> Removed two duplicate words from ./wordlist.

- makefile
The following warning was printed by awk, when running 'make spell':
awk: cmd. line:1: warning: regexp escape sequence `\&' is not a known
regexp operator
This patch removes the escape in front of the '&' in the awk regexp
and fixes this issue.
> Fixed an awk regexp escape sequence warning in the makefile.

- .github/workflows/pull_request.yml
- commands/acl-setuser.md
- commands/client-caching.md
- commands/eval.md
- commands/module-load.md
- commands/stralgo.md
- commands/xreadgroup.md
- wordlist
After @wingunder's #1399, #1400 \& #1401 (ty), it seemed like a good idea to vet out the existing spelling errors and re-introduce the spell check on PRs.
> Re-establishes the use of `make spell`

- makefile
Spell checking by the 'spell' makefile target is done by using
white-list words originating from commands in the ./commands.json file
as well as words in the ./wordlist file. Two ways of word duplication
in these two files are possible:
1. A new command gets added to the ./commands.json file, while the
command already exists in the ./wordlist file.
2. The same word simply exist twice inside the ./wordlist file.
This patch adds two makefile targets that check for these two cases,
when running 'make spell'.
> Added make-check-targets for duplication inside the ./wordlist file.

- commands.json
- commands/zadd.md
- topics/modules-api-ref.md
Per the pull request in the main redis repository:
https://github.com/redis/redis/pull/7818
This is an update to the documentation describing the GT and LT options for the ZADD command.
> Documentation update for new ZADD GT and LT options

- commands.json
- commands/getset.md
- commands/set.md
Closes #2349
Add optional GET parameter to SET command in order to set a new value to
a key and retrieve the old key value. With this change we can deprecate
`GETSET` command and use only the SET command with the GET parameter.
> Add GET parameter to SET command

- commands/set.md
- commands/setnx.md
- topics/clients.md
- topics/cluster-spec.md
- topics/data-types-intro.md
- topics/indexes.md
- topics/lru-cache.md
- topics/memory-optimization.md
- topics/partitioning.md
- topics/pipelining.md
- topics/quickstart.md
- topics/twitter-clone.md
On some pages, Firefox shows a warning in the url bar when visiting the website over https, caused by images being loaded over http.
For the sake of completeness, here I've moved all internal links to use https scheme.
> Rewrite all links to redis.io with https scheme.

- topics/sentinel.md
Note: This PR is for review only since In line 790 I left a placeholder for the redis version for releasing ACL on Sentinel. We can replace it with correct version once this is released.
> update sentinel doc for adding ACL authentication

- commands/client-list.md
after https://github.com/redis/redis-doc/pull/1440 I found user field is also missing in CLIENT LIST command.
> add missing user information in client list

- commands.json
- commands/command.md
- commands/zdiff.md
- commands/zdiffstore.md
- topics/notifications.md
Add documentation for the new commands added in https://github.com/redis/redis/pull/7961
I took the liberty to also add missing entries for the zinter and zunion commands in the "Movable Keys" section of COMMAND.
There's one thing I need help with: the complexity of these new commands. My math skills are rusty, so I didn't even try very hard to check it. I just adapted the complexity of SDIFF, but I'm thinking it is too broad, or maybe even incorrect. Basically, ZDIFF and SDIFF use the same algorithms, which can be one of two depending on the size of the input sets. I thought about just doing `O(min(a, b))`, but maybe there's a better way. The complexity stated in the documentation is the one from algorithm 2 in the code.
> Add documentation for the new zdiff/zdiffstore commands

- clients.json
Hello - this is to add a [client I maintain](https://npmjs.com/package/handy-redis) to clients.json
I also re-ordered some of the clients and updated some "active" flags (rough method I used: no activity for >1 year and very few downloads => not active).
> Add handy-redis to list of clients

- topics/distlock.md
The current listed PHP implementation are all synchronous; this pull request introduces a link for a non-blocking implementation built on top of ReactPHP.
> Add asynchronous Redlock PHP implementation

- commands.json
- commands/xadd.md
- commands/xtrim.md
Relies on https://github.com/redis/redis-io/pull/221
Should fix #1007, #1008 and wrt to https://github.com/redis/redis/pull/7972#issuecomment-730867094
Also adds `XADD ... NOMKSTREAM` (https://github.com/redis/redis/pull/7910).
`XADD` before/after shots:
`XGROUP` before/after shots:
`XPENDING` before/after shots:
> Adds nested arguments

- clients.json
Redis and Redis Cluster in particular are used by Ericsson. Forks
of no longer active clients in C and Erlang are now maintained by
the Nordix Foundation with support by Ericsson.
This commit adds these forks and marks the original clients as inactive
and in some case as not recommented.
> Clients: Add forks of C and Erlang clients and mark old as inactive

- topics/distlock.md
Hello, folks!
I've been working on my own [set of Pythonic Redis utilities](https://github.com/brainix/pottery), and my library includes a Redlock implementation, so I thought I'd add it to the list. How does it look?
Thanks!
Raj
> Add Pottery Redlock implementation

- commands/info.md
This PR documents the soon to be added fields to the `INFO` command on PR https://github.com/redis/redis/pull/8132. Apart from it, tried to make more clear the differences between (`used_cpu_sys` and `used_cpu_sys_main_thread`), and ( `used_cpu_user` and `used_cpu_user_main_thread` )
> Documented redis#8132: Redis main thread cpu time, and scrape system time

- topics/cluster-tutorial.md
I believe this port should be `7002` in the example, since it is shown after:
```
redis 127.0.0.1:7000> get foo
-> Redirected to slot [12182] located at 127.0.0.1:7002
"bar"
```
> change port to 7002 after redirection

- commands/lpos.md
To keep it consistent I decided to use the same wording as used for `Count` 0
Fixes #1429
> Clarify the usage of maxlen with a value of 0

- topics/acl.md
Removes the hypothesis made over HELLO command' evolution : << will probably provide a SETNAME option soon >>
As the documentation page settles that the option is available (Available since 6.0.0).
+Line364: ordering/eases reading sentence
> abide current HELLO subcommand

- commands/brpoplpush.md
- commands/georadius.md
- commands/georadiusbymember.md
- commands/geosearch.md
- commands/geosearchstore.md
- commands/getset.md
- commands/hmset.md
- commands/rpoplpush.md
also replace test in existing deprecatoin notes with "prefer", since the
new commands may not be supported by the client libraries.
> add command deprecation note for GEORADIUS

- commands/info.md
- wordlist
The following PR documents the added features in https://github.com/redis/redis/pull/8217 ( the new errorstats section and a new global error counter ).
> Added documentation regarding error statistics (redis/redis#8217)

- tools.json
PrestoSQL was rebranded as Trino: https://trino.io/blog/2020/12/27/announcing-trino.html
> Rename Presto SQL to Trino

- commands.json
- commands/zrange.md
- commands/zrangebylex.md
- commands/zrangebyscore.md
- commands/zrangestore.md
- commands/zrevrange.md
- commands/zrevrangebylex.md
- commands/zrevrangebyscore.md
i'm not very comfortable with how this came out.
documenting all the nuances and instructions of BYSCORE / BYLEX / BYRANK in one page can make it quite complex.
instead i added a note to refer to the documentation of the deprecated commands for details (which sounds like a bad idea).
maybe that's a hint that this change is all wrong?
i.e. there are a lot of details about inclusive / exclusive searches and how the lexicographic ordering works, maybe unifying them into one command is wrong?
> New ZRANGESTORE and ZRANGE new args, deprecate others

- commands/client-kill.md
- commands/client-list.md
- commands/monitor.md
- commands/subscribe.md
- commands/zadd.md
Made @history consistent, since it was brought up in another PR. No need have people copy the wrong format.
> Fixed consistency issue with history versions

- clients.json
Adding [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster) to the list of the Python clients.
> Adding redis-py-cluster to the list of clients.

- clients.json
With no activity in the repo for a year, it hasn't met the "Clients with some activity in the official repository within the latest six months" criteria for some time.
I kept the `recommended` flag for now, as I'm not sure who decides that and based on what.
Also updated the name from node_redis to node-redis.
> clients.json: marked node-redis as inactive

- commands/stralgo.md
currently STRALGO LCS syntax spec is:
```
STRALGO LCS [KEYS ...] [STRINGS ...] [LEN] [IDX] [MINMATCHLEN <len>] [WITHMATCHLEN]
```
which IMHO is not accurate, and might be confusing:
- `KEYS ...`, `STRINGS ...`  seems like the LCS algo can accept arbitary number of KEY or STRING
- ` [KEYS ...] [STRINGS ...]` seems like LCS can accept either `KEYS`, `STRINGS` , or both or neither
I suggest 'the one' used in the source code comment(accually 'the one' also missed LEN option):
```
STRALGO LCS STRINGS <string_a> <string_b> | KEYS <key_a> <key_b> [LEN] [IDX] [MINMATCHLEN <len>] [WITHMATCHLEN] 
```
> specify STRALGO LCS sytax more accurately.

- commands.json
- commands/reset.md
Fix RESET command sets the connection to READWRITE instead of READONLY.
Add LADDR in command CLIENT LIST.
> Fix RESET command misleading typo and add CLIENT KILL LADDR

- commands/xack.md
- commands/xautoclaim.md
- commands/xclaim.md
- commands/xgroup.md
- commands/xinfo.md
- commands/xpending.md
- commands/xreadgroup.md
Corrected some minor issues which might help others when going through the descriptions of the stream commands:
- Source code only mentions `pending entries list` which is now used in docs.
- Use of `@examples` and `@return`
- State the different return types for the different forms of `XGROUP`
> Stream command cleanups

- commands/geoadd.md
The prompt of command GEOADD in redis-cli (6.2.1) is:
> GEOADD key [NX|XX] [CH] longitude latitude member [longitude latitude member ...]
> Fix wrong order of geospatial tuple

- commands/xack.md
redis.io page was showing interactive cli for XACK which is blocked and through an error in the response. I removed the cli tag and fixed the example to show how it would look to the user
> Remove cli tag from XACK

- topics/config.md
Describe strings format in `redis.conf` according to the way how it is
treated by the configuration parsing logic.
> Add more details about configuration format

- commands.json
WITHCOORD, WITHDIST and WITHHASH are not meant to be supported since this command a STORE command, which doesn't support those args.
Fixes issue #8864
> Remove WITHCOORD, WITHDIST and WITHHASH

- commands/zremrangebylex.md
I find that "remove" better suits the actual meaning here, as `ZRANGEBYLEX` doesn't actually return any values.
> ZREMRANGEBYLEX : Replace "return" with "remove"

- commands.json
- commands/expiretime.md
- commands/pexpiretime.md
Add API documentation for `EXPIRETIME` and `PEXPIRETIME` commands introduced in this PR: https://github.com/redis/redis/pull/8474
> API documentation of EXPIRETIME and PEXPIRETIME commands

- commands/cluster-nodes.md
`nofailover` flag  not updated.
> Add missing flag nofailover in "cluster nodes" command output.

- commands/set.md
Merge after https://github.com/redis/redis/pull/8906
~~I think it would also make sense to clear up the segment "Return value" as it is currently ambiguous whether `EX`/`NX` or `GET` have priority on what's returned.~~
> Update SET documentation for NX and GET

- topics/cluster-tutorial.md
When reading the docs, I noticed that there is a space before the dot at the end of the sentence.
> Removed wrong space

- commands/zadd.md
Reference https://stackoverflow.com/questions/67486957/syntax-error-when-making-redis-call-from-lua
> That "Always" was confusing to me, should probably be "Only"
> Rephrase description of XX and NX options of ZADD

- clients.json
Hello redis-doc admins!
I have developed a new Redis client in Julia and would like to add it the list of available Redis clients.
`Jedis.jl` is a a registered packaged, it can be found [here](https://github.com/JuliaRegistries/General/tree/master/J/Jedis) on the Julia general registry. Documentation for the client interface can be found [here](https://captchanjack.github.io/Jedis.jl/).
Let me know if there is anything needed to get this PR in!
Cheers,
Jack
> Add `Jedis.jl` to clients.json as a new Julia client

- clients.json
Adding a new redis cluster client in erlang.
Some key features
* uses eredis as underlying implementation
* allows connections to multiple clusters at the same time
* queries don't get handled on the cluster-gen-server process they get directed to right eredis client.
> Adding ecredis - Erlang Redis Cluster client.

- clients.json
The only existing Bash client featured in https://redis.io/clients#bash, viz. [Redi.sh](https://github.com/crypt1d/redi.sh), is very limited in scope and not very extensible. Although written in Bash, Redi.sh depends unnecessarily on various Unix tools rather than using Bash native functionalities mostly.
The present [client](https://github.com/SomajitDey/redis-client), on the contrary, is written from scratch with a strong focus on using Bash functionalities as much as possible. This adds to its performance and portability. It is also extensible, and currently has full support for any Redis command execution in the request-response mode.  Support for pipelining and push protocol would be added in near future.
The client library also supports creating a Redis session and keeping it alive, …
> Added redis-client (Bash): https://github.com/SomajitDey/redis-client

- commands.json
Commands that support multiple arguments and have a time complexity of O(1) for a single argument, such as, DEL, HDEL, HMGET, HMSET, MGET, MSET, MSETNX, SADD, and SREM, have a time complexity of O(N) where N is the number of arguments.
I believe that the time complexities of EXISTS, LPUSH, and RPUSH were not updated when support for multiple arguments was added to each command. The respective lines of code that I think support this change are: [EXISTS](https://github.com/antirez/redis/blob/33769f840cd53f03caf8f4b886a7c95182492027/src/db.c#L327), and [LPUSH & RPUSH](https://github.com/antirez/redis/blob/33769f840cd53f03caf8f4b886a7c95182492027/src/t_list.c#L206).
SPOP is more complex but very similar to SRANDMEMBER, so I believe that the time complexity of …
> Update time complexity of EXISTS, LPUSH, RPUSH, SPOP

- README.md
- clients.json
Add a new client: redis-async for ocaml.
Document at dependency on the ruby gem 'batch'
> New client: redis-async

- commands/scan.md
Small correction on the docs to improve understanding and legibility.
> Address documentation typo on parallel iterations

- commands/cluster-addslots.md
- commands/cluster-delslots.md
- commands/cluster-nodes.md
- commands/cluster-setslot.md
- topics/cluster-spec.md
- Fix redis-cli reference instead of redis-trib;
- redis-cli use multiple keys MIGRATE instead of single key MIGRATE;
- One failover target error in cluster spec.
> Some minor fix in cluster

- topics/performance-on-cpu.md
This page describes a set of instruments to identify performance regressions and/or potential **on-CPU performance** improvements 
------------
This document focus specifically **on CPU** resource bottlenecks analysis, meaning we're interested in understanding where threads are spending CPU cycles while running on-CPU, and as important wether those cycles are effectively being used for computation or stalled waiting (not blocked!) for memory I/O, and cache misses, etc...
For that we will rely uppon toolkits (perf, bcc tools), and hardware specific PMCs (Performance Monitoring Counters), to proceed with:
- Hotspot analysis ( pref or bcc tools ): to profile code execution and determine which functions are consuming the most time and thus are targets for optimization. We'll present two …
> Kicked off performance analysis guide - on CPU profilling and tracing

- commands.json
This moves the 6 bit-related commands from the 'string' to a new
category. The motivation is giving more exposure for these lesser-
known capabilities.
@antirez - your thoughts?
TODO:
[ ] Add Bit group in redis-io/lib/reference.rb
> Moves some commands to a new 'bit' category

- topics/sentinel.md
We have a new INFO field for Sentinel sentinel_tilt_since_seconds according to the redis pr request https://github.com/redis/redis/pull/9000
> new INFO field for Sentinel

- commands/info.md
Add info metrics total_eviction_exceeded_time and
current_eviction_exceeded_time. See
https://github.com/redis/redis/pull/9031.
> Add info metrics about redis#9031

- topics/acl.md
Fixes #1598
adds a detailed description of the meaning of each ACL category.
text copied from the recently improved redis.conf
> add description of the ACL categories

- commands/info.md
the details about `mem_fragmentation_ratio`, and `activedefrag_running` where misleading.
added lost of info about the breakdown of different RSS related metrics.
> INFO details about fragmentation

- commands/client-pause.md
Without the blank line, all elements in the list is rendered as a paragraph.
> Render lists properly in CLIENT PAUSE doc

- commands/client-pause.md
(This is the American vs British spelling)
It looks like this broke because it wasn't correctly parsing the markdown in the past, when the markdown was fixed the rest of the block was parsed correctly.
> Fix spelling of acknowledgment

- commands/info.md
In https://github.com/redis/redis/pull/8974, we add `current_cow_peak field` in INFO command
> Add current_cow_peak field in INFO command

- commands/eval.md
- wordlist
Also cleaned up and clarified other text in the
replication section of the EVAL command.
Co-Authored-By: Viktor Söderqvist <viktor.soderqvist@est.tech>
Replaces #695. Fixes #693.
> Avoid confusing use of term "pure function"

- commands.json
- commands/georadius.md
- commands/sort.md
- commands/sort_ro.md
In addition, corrected use of hyphen in "read-only" for similar GEORADIUS doc
> Add SORT_RO documentation

- commands/cluster-failover.md
- topics/cluster-tutorial.md
Some notes are added to CLUSTER FAILOVER command and to the Cluster
Tutorial document, regarding manual failover to a new, just added,
replica.
This scenario was discovered while automating node upgrades using
manual failover.
> Notes on manual failover to a new (just upgraded) replica

- topics/distlock.md
Escape markdown in the string "my_random_value" in the distributed locks page.
> Escape markdown in my_random_value

- commands/pubsub.md
Clarifying the return type of pubsub numpat.
Related to this change: https://github.com/redis/redis/pull/9209
> Clarify what pubsub numpat behavior change

- commands/monitor.md
Updating `MONITOR` docs to match that some commands are now included in the output.
Changed since 6.2.4 via https://github.com/redis/redis/pull/8859
> Update MONITOR command

- commands.json
Temp workaround for  https://github.com/redis/redis-io/issues/251
Introduced to `BITFIELD_RO` command in #1645
> Temp workaround for bug BITFIELD_RO in command doc

- topics/acl.md
Sorts the list of categories lexicographically (and make them bold)
Fix some formatting issues with ul/ol and tabs
> Fixes formatting and sorting to ACL man page

- topics/config.md
Happened to see that 6.2 is missing the redis.conf link.
Also with minor fixes in config documentation.
> Add 6.2 redis.conf link

- commands.json
Hi, I found a little inconsistent in the comments.json. I think `id` argument in the `XGROUP SETID` should be labeled as `type=enum` to align with others.
> Correct XGROUP SETID enum type argument definition in comments.json

- topics/modules-intro.md
The example uses 1234 as argument. But, on the other hand, description explains using 123.
```
loadmodule mymodule.so foo bar 1234
```
So I fixed inconsistency between example about how to run and description
> fix inconsistency between example about how to run and description

- commands.json
- commands/cluster-info.md
- commands/cluster-links.md
- commands/info.md
* Add API documentation for `CLUSTER LINKS` command;
* Add `mem_cluster_links` field to API document of INFO command;
* Add `total_cluster_links_buffer_limit_exceeded` field to API document of CLUSTER INFO command
Related Redis changes: https://github.com/redis/redis/pull/9774
> Add API documentation for CLUSTER LINKS command

- commands/info.md
see: https://github.com/redis/redis/blob/unstable/src/server.c#L4488
> io_threads_active field should belong to server instead of clients

- topics/protocol.md
https://redis.io/topics/protocol
I would like to enclose it in double quotes, like other places
> Use " instead of ` for better readability in protocol.md

- commands/client-list.md
multi-mem: added in redis/redis#8687
resp: added in redis/redis#9508
Also adjust the order of fields to better match the output
The current output format is (redis unstable branch):
```
id=3 addr=127.0.0.1:50188 laddr=127.0.0.1:6379 fd=8 name= age=7 idle=0
flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10
multi-mem=0 obl=0 oll=0 omem=0 tot-mem=40986 events=r cmd=client|list
user=default redir=-1 resp=2
```
> Add multi-mem and resp in CLIENT LIST

- commands.json
- commands/zrange.md
Accompanying PR to redis/redis#10097 to change `min` -> `start` and `max` -> `stop` in `ZRANGE` see other PR for explanation for change.
> zrange min->start max ->stop

- commands/info.md
#1748 shutdown_in_milliseconds. Added in https://github.com/redis/redis/pull/9872
> Fix shutdown_in_milliseconds wrong name in INFO

- topics/streams-intro.md
1. Fixed some typos.
2. Use `` instead of **** for commands, so that we can
generate a hyperlink to jump to the command page.
> streams-intro doc cleanups

- commands/info.md
- commands/memory-stats.md
#1748 aof_rewrite_buffer_length, removed in https://github.com/redis/redis/pull/9788
> Added comment that `aof_rewrite_buffer_length` was removed in 7.0

- topics/pubsub.md
This change adds RESET to the list of allowed commands a client can
issue in a subscribed context. After this change the list of commands
will be consistent with the list specified for [SUBSCRIBE][subscribe],
and also the allowed commands as specified by the implementation.
https://github.com/redis/redis/blob/a43b6922d1e37d60acf63484b7057299c9bf584d/src/server.c#L3626-L3637
[subscribe]: https://redis.io/commands/subscribe
> topics/pubsub: add RESET to allowed commands for subscribed client

- commands/info.md
`server_time_usec`, added in https://github.com/redis/redis/pull/8132
now in redis-doc is `server_time_in_usec`, added in #1455
#1748 server_time_usec
> Fix wrong server_time_usec INFO field name

- commands/eval_ro.md
Redis7.0 RC1
```
127.0.0.1:6379> EVAL_RO "return redis.call('DEL', KEYS[1])" 1 mykey
(error) ERR Error running script (call to b0d697da25b13e49157b2c214a4033546aba2104): @user_script:1: @user_script: 1: Write commands are not allowed from read-only scripts.
```
In Redis7.0 FUNCTION changes, now the error reply does not contain 'f_'.
https://github.com/redis/redis/blob/f4ecc799c87fa504b375afc17a7f8302789254b5/src/eval.c#L506-L514
```
char *lua_cur_script = funcname + 2;           ----------- here
dictEntry *de = dictFind(lctx.lua_scripts, lua_cur_script);
luaScript *l = dictGetVal(de);
int ro = c->cmd->proc == evalRoCommand || c->cmd->proc == evalShaRoCommand;
scriptRunCtx rctx;
if (scriptPrepareForRun(&rctx, lctx.lua_client, c, lua_cur_script, l->flags, ro) != C_OK) {
return;
}
``` …
> Error message method name now does not contain 'f_'

- commands/info.md
- topics/persistence.md
Fix multipart aof backup doc to use `aof_backup.sh` script for safe aof backups since v7.
See https://github.com/redis/redis/pull/10178
> fix multipart aof backup doc

- commands/function-load.md
Extra pair of parentheses, the rendered html is:
`<a href="/topics/lua-api#redis.register_function(">`
> Fix error hyperlink in function-load

- topics/lru-cache.md
"most" is a generic qualifier, so the sentence under revision may currently be read in at least two distinct ways:
1.  "the access that was **accessed the most** in the past"
2. "the access that was accessed the **most in the past**"
The first interpretation refers to a key that was most frequently accessed in some unspecified past period.
The second interpretation refers to a key that was accessed earlier than any other candidate key. This is, I think, the correct interpretation. 
"furthest" is not as generic a qualifier, and can't really be bound to the _amount_ of accesses, so the first (and incorrect) interpretation is avoided. "Furthest" is a distance qualifier, applicable to both space and time. In this case, time.
> Change word to reduce ambiguity in 'LRU cache' page sentence.

- commands.json
- commands/command-getkeys.md
- commands/command-getkeysandflags.md
- topics/key-specs.md
- topics/modules-api-ref.md
doc changes for https://github.com/redis/redis/pull/10237
> GETKEYSANDFLAGS sub-command, new module apis, and key-spec flags changes

- topics/persistence.md
Updated AOF backup docs not to mention a script and simply explain you can disable aof rewrites and then do the backup safely.
> multipart aof backup details without script

- topics/lua-api.md
> Corrects named args syntax for redis.register_function

- topics/eval-intro.md
- "exectue" changed to "execute"
> fix typo in eval-intro

- commands/cluster-set-config-epoch.md
- topics/cluster-spec.md
I am sure there is no `CONFIG SET-CONFIG-EPOCH`.
> Fix the wrong CLUSTER SET-CONFIG-EPOCH command name

- commands/cluster-keyslot.md
Add `(integer)` to be more accurate and consistent
> Fix cluster-keyslot example

- topics/protocol.md
Mirror of https://github.com/redis/redis-specifications/pull/4. I'm not sure which is the source of truth.
> Was making a toy Redis server in Java (https://app.codecrafters.io/courses/redis) which had me reading the spec at [redis.io/topics/protocol](https://redis.io/topics/protocol).
> 
> This sentence didn't make sense to me, so I've edited in what I think is the intended meaning.
> "are" -> "as". Fix word use in spec.

- docs/manual/cli.md
Fix typo `praenthesis ` in `docs/manual/cli`
> Fix typo `praenthesis` in `docs/manual/cli`

- commands/sort.md
1. Add notice that 'GET' and 'BY" options are not valid for cluster-mode
2. Add notice for 'GET' and 'SET' options are not valid when no
Full key read permissions
> add sort command new acl documentation

- commands/client-pause.md
- commands/cluster-slots.md
- commands/flushall.md
- commands/flushdb.md
- commands/monitor.md
- commands/rename.md
- commands/script-flush.md
- commands/shutdown.md
- commands/subscribe.md
Added a section for behavior change history as a replacement for https://github.com/redis/redis/pull/10398.
> Added behavior change history section to commands

- docs/reference/patterns/distributed-locks.md
spelling error: "desceibes" => "describes"
> Spelling error in distributed.locks.md

- docs/manual/security/acl.md
mostly broken links due to subcommand being quoted without command name.
plus some typos.
> acl doc cleanups

- docs/manual/programmability/eval-intro.md
- docs/manual/programmability/lua-api.md
Adds documentation for a new lua flag, `allow-cross-slot-keys` which is implemented here: https://github.com/redis/redis/pull/10615
> Added allow-cross-slot-keys flag

- commands/fcall.md
Fixes the example shown in the FCALL section. Corrects the `FUNCTION LOAD` command invocation.
> Fix the example in the FCALL section

- docs/manual/programmability/eval-intro.md
- Made some grammatical changes to `redis-doc/docs/manual/programmability/eval-intro.md`.
> resolved typos in eval-intro.md

- commands/ssubscribe.md
Update multi channel subscription behaviour for `SSUBSCRIBE`.
ref [10599](https://github.com/redis/redis/issues/10599)
> Multi channel subscription behaviour for SSUBSCRIBE.

- docs/reference/key-specs.md
We do have a `title: "Command key specifications"` in the front.
So this one will render an extra title, remove it.
> Remove extra title in key-specs page

- community/index.md
Ironically a markdown error is currently providing an incorrectly-rendered link to redis docs :')
> Fix broken link to redis docs on community page

- clients/python/github.com/alisaifee/coredis.json
[coredis](https://github.com/alisaifee/coredis) was forked from [aredis](https://github.com/NoneGG/aredis) as the latter had become unmaintained since 2020.
- coredis [2.x](https://github.com/alisaifee/coredis/tree/2.x) refreshed aredis with support for python 3.10 and brought in some outstanding pull requests/bug fixes.
- coredis [3.x](https://coredis.readthedocs.org/en/latest) has diverged from aredis and is no longer API compatible. It adds support for redis 7, type annotations, RESP3 support among others.
As a follow up I would also recommend marking aredis as unmaintained.
> Add coredis library to python clients

- commands/xdel.md
Sub-chapter used level 1 header when in other pages sub-chapters use level 2 headers
> Fix header level for XDEL page

- docs/manual/pubsub.md
The Pub/Sub link on the [About](https://redis.io/docs/about/) page redirected to /docs/manual/pub-sub instead of /docs/manual/pubsub, which caused a 404. This new alias should fix the 404.
> Added pub-sub alias

- commands/eval_ro.md
- commands/evalsha_ro.md
- commands/fcall_ro.md
- docs/manual/programmability/_index.md
- docs/manual/programmability/eval-intro.md
Based on discussion from https://github.com/redis/redis/pull/10728#issuecomment-1127313929, want to better define when to use `EVAL` et. al vs `EVAL_RO` et al.
> Add documentation documenting read-only scripts

- commands/info.md
add 3 info fields which is brought in https://github.com/redis/redis/pull/10062.
> Add info fields about network bytes during replication.

- docs/manual/programmability/lua-api.md
The typo can be seen on this page: https://redis.io/docs/manual/programmability/lua-api/#data-type-conversion
> Fix typo in lua-api.md

- docs/manual/persistence.md
There was a capitalized The in the middle of the sentence.  If it is not a convention, it must have been a typo.
> Fixing a typo in docs/manual/persistence.md

- clients/python/github.com/Grokzen/redis-py-cluster.json
- clients/python/github.com/NoneGG/aredis.json
- clients/python/github.com/aio-libs/aioredis.json
Follow up from #1885 to remove obsoleted python clients from documentation:
> Remove obsolete python clients

- docs/manual/transactions.md
Back ticks cause the command to be a link. This messes up the formatting in the "On This Page" section.
> Remove backticks around WATCH in titles

- commands/cluster-meet.md
cluster meet command format as below:
cluster meet ip port [cport], cport as an optional argument is missing.
> Update cluster-meet command for cport argument

- docs/manual/security/acl.md
- *ACL LIST* designed for computers
- *ACL GETUSER* is more human readable
> Fixes redis/redis-doc#2022 ACL LIST to ACL GETUSER

- docs/reference/protocol-spec.md
While writing a RESP parser in Rust, I copied some of the examples from the docs to use in my tests. 
When adding validation to my code I noticed a bulk string had the incorrect length.
> Fix typo in RESP protocol example

- docs/manual/eviction.md
Now we won't do anything on counter if lfu-decay-time is 0.
see https://github.com/redis/redis/pull/11108
> Fix outdated lfu-decay-time doc in eviction.md

- docs/data-types/sets.md
The former link points to the Redis Lists Explained video.
> Fix incorrect link to Redis Sets Explained video

- docs/reference/patterns/indexes.md
Modify `ZRANGEBYLEX`, `ZRANGEBYSCORE`, `ZREVRANGEBYSCORE` commands that is regarded as deprecated on Redis 6.2.0 to `ZRANGE` with `BYLEX`, `BYSCORE`, `REV` arguments
#2043
> Modify deprecated 'ZRANGE*' command in reference/patterns

- docs/data-types/sets.md
Ran into this bit of raw markdown while reading the docs this morning:
> fix a markdown link syntax issue

- docs/data-types/streams.md
> Fix typo on streams

- docs/manual/cli.md
This fixes a small typo (I believe after a `s/ping/PING/g`?) that had me wondering for a few seconds what a tyPING was, until I realised the typo. :)
> Fix inconsistent tyPING -> typing

- docs/manual/persistence.md
There is duplicated explanation about backing up AOF persistence.
https://github.com/redis/redis-doc/blob/master/docs/manual/persistence.md?plain=1#L334-L377
This CR is for removing redundant explanation.
> Remove duplicated explanation about backing up AOF persistence

- docs/manual/security/acl.md
currently `config get requirepass` still returns raw password instead hashed one.
> remove stale info about config get requirepass

- commands.json
corresponding to:
* https://github.com/redis/redis/pull/11157
* https://github.com/redis/redis/pull/11169
* https://github.com/redis/redis/pull/11162
* https://github.com/redis/redis/pull/10970
* https://github.com/redis/redis/pull/11026
* https://github.com/redis/redis/pull/11017
* https://github.com/redis/redis/pull/11015
* https://github.com/redis/redis/pull/10988
> updated for commands.json from redis 7.0.5

- modules/community/github.com/ekzhang/redis-rope.json
Adding my new [redis-rope](https://github.com/ekzhang/redis-rope) module to the list.
> Add redis-rope to the community modules list

- clients/ruby/github.com/redis-rb/redis-client.json
- clients/ruby/github.com/redis-rb/redis-cluster-client.json
- clients/ruby/github.com/redis/redis-clustering.json
Hello,
We implemented two clients for Ruby. They were made by the same maintainers as [the redis gem](https://rubygems.org/gems/redis). They are geared toward Redis version 6 or later.
* https://github.com/redis/redis-rb/issues/1070
* https://rubygems.org/gems/redis-client
* https://github.com/redis-rb/redis-client
* https://rubygems.org/gems/redis-cluster-client
* https://github.com/redis-rb/redis-cluster-client
* https://rubygems.org/gems/redis-clustering
* https://github.com/redis/redis-rb/tree/master/cluster
> Add redis-client and redis-cluster-client to Ruby clients

- docs/manual/cli.md
I found type and would like to fix for better documentation.
readibility -> readability
`redis-cli`in -> `redis-cli` in (adding white space)
Thanks!
> Update cli.md for typo fix

- docs/data-types/sorted-sets.md
There was a missing word in the documentation for sorted sets. I added the missing word in both sentences.
> Doc: fix grammer error

- docs/data-types/geospatial.md
The example shows how to get all locations within a radius of 5 km, but the text says within 1 kilometer.
This PR will update the text to be in line with the example.
> Fix radius in GEOSEARCH example

- docs/reference/internals/internals-rediseventlib.md
Fixes invalid markdown syntax of a link on `docs/reference/internals/internals-rediseventlib.md`
> Fix invalid markdown link

- commands/quit.md
> Add note to QUIT that clients should not use it

- commands/lastsave.md
A small note about an edge case that can lead the described procedure to hang indefinitely if BGSAVE returned the same second that redis started.
> Add note about LASTSAVE without previous BGSAVE

- libraries/go/github.com/go-redsync/redsync.json
Redsync implements the Redlock algorithm in Go. The [distlock article on redis.io](https://redis.io/topics/distlock/) mentions this package as the reference Go implementation. This Go package is actively maintained and is being used in some other noteworthy open source projects.
https://github.com/go-redsync/redsync
> Add Redsync: Implementation of Redlock in Go

- commands/xrange.md
Everywhere across the docs, as well in the Redis University course RU202, it's stated that the minimal possible id is `0-1`, but not `0-0`
> docs: correct minimum possible id

- clients/bash/github.com/caquino/redis-bash.json
Hi, 
This PR adds [redis-bash](https://github.com/caquino/redis-bash) to the list of clients.
This PR addresses [this issue](https://github.com/caquino/redis-bash/issues/13) opened on [redis-bash](https://github.com/caquino/redis-bash) repository.
Also, thanks for all the work for the community!
Thanks, @zuiderkwast for the suggestion, and sorry for taking so long. 
Not sure why I was not notified about the `issue`, I will review my notification preferences.
> add redis-bash to list of clients.

- docs/data-types/tutorial.md
- docs/manual/pubsub.md
setbit return the original bit value stored at offset, so `setbit key 10 1` should return 0.
> fix: setbit should return 0 on an empty instance

- clients/swift/github.com/michaelvanstraten/Swifty-Redis.json
Dear Redis Developer Team,
A few months back I was developing a swift app for which I needed a Redis client. 
I took a look at the https://redis.io/resources/clients/#swift recommended clients,
but I could not find one that integrates well with the current async await standards of swift. 
I decided to develop my own client using the new asynchronous swift concurrency framework.
Would it be possible to list my package under the list of available clients?
Some of the features of this package include:
- 240 command implemented and documented
- adheres to Redis 7.0 standard
- implements modern swift concurrency
- offers vast documentation using apple docC framework (tutorial section not completed) 
- easily extendable
- generic type system for return type
maybe some could take a look at it. …
> Added SwiftyRedis as a swift client

- commands.json
- commands/zrank.md
- commands/zrevrank.md
- wordlist
For PR redis/redis#11235, which adds the `WITHSCORE` option to command `ZRANK` and `ZREVRANK`.
Add description of option `WITHSCORE` argument to `zrank.md` and `zrevrank.md`.
Modify `commands.json`.
> Add description of WITHSCORE argument to ZRANK and ZREVRANK.

- commands/memory-usage.md
Adds an extra statement to make clearer that N samples are averaged and then the result is multiplied by nested key's cardinality. The docstring for the function has this extra specificity, so this change just carries it over into the docs: https://github1s.com/redis/redis/blob/HEAD/src/object.c#L992.
> Update MEMORY USAGE doc to be more specific about SAMPLES

- commands/psubscribe.md
- commands/punsubscribe.md
- commands/ssubscribe.md
- commands/subscribe.md
- commands/sunsubscribe.md
- commands/unsubscribe.md
See related discussion in redis/redis#11784.
> Notes on what *SUBSCRIBE returns (or doesn't return)

- commands/hello.md
Removes the last reference to the old RESP3 specification site.
> Use correct link to the RESP3 specification

- docs/manual/patterns/twitter-clone.md
The original author writes usefully yet elitistly about decision to use PHP: "I used PHP for the example since it can be read by everybody. The same (or better) results can be obtained using Ruby, Python, Erlang, and so on." I am suggesting a rephrasing of the first sentence so that everyone feels more welcome to this tutorial, even those of us who may not be reading PHP well. --> New sentence is: "I used PHP for the example because of its universal readability."
> More inclusivity in prior knowledge assertions -- using passive tone is less intimidating!

- clients/scala/github.com/jodersky/redicl.json
This is [a relatively new client for Scala that I created](https://github.com/jodersky/redicl). It uses only the standard Scala library, is minimal but still very expressive (somewhat inspired by the Python client's API).
> Add jodersky/redicl client

- commands.json
- commands/client-setinfo.md
also update commands.json with XINFO history
> add docs for CLIENT SETINFO

- docs/manual/programmability/lua-api.md
Clarify error code conventions for Lua scripts, and make the example more correct.
Discussed in redis/redis#11976.
> Clarify error code conventions for Lua.

- docs/getting-started/installation/install-redis-on-mac-os.md
On the Install Redis on macOs page the command to check brew version contains $ in its line. Since rest of the commands given in the document start directly from brew and not $ brew as $ is already present in the terminal it will be easier to just keep brew --version so that the user can directly copy that command in their terminal, else they'll have to remove $ from the command line manually. This seems much easier from a user's perspective to copy directly and paste the command without failure.
> removal of $ from $ brew -version command

- commands/waitaof.md
Description was worded in a way that might have made it unclear the command would only wait for write commands _by the same client_ that executed it.
> Clarify WAITAOF documentation

- commands/info.md
These fields was added in https://github.com/redis/redis/pull/11012
> Add new total_blocking_keys and total_blocking_keys_on_nokey fields in INFO

- commands/memory-usage.md
The most recent related PR is this: https://github.com/redis/redis/pull/9095
> Update MEMORY USAGE examples to latest version

- modules/community/github.com/sewenew/redis-llm.json
Add [redis-llm](https://github.com/sewenew/redis-llm) module to community module list. This module helps LLM to access private data, and remember long chat history.
> Add redis-llm to community module list

- clients/ruby/github.com/etehtsea/oxblood.json
This client is public archived on GitHub: https://github.com/etehtsea/oxblood
> Remove archived ruby client

- commands/cluster-nodes.md
In redis/redis#12411 the format of the return of `CLUSTER NODES` is modified. And we need to correct the doc here.
I deleted the description about auxiliary fields in this page, but I don't find it anywhere else. I think we still need to doc it somewhere, maybe in a page specifically for the nodes.conf file.
> Update doc of command CLUSTER NODES.

- docs/management/security/acl.md
It's one of ACL categories and I guess it's a typo right?
> Fix typo (`@readonly` -> `@read`)

- clients/csharp/github.com/redis/NRedisStack.json
- clients/go/github.com/redis/go-redis.json
- clients/java/github.com/redis/jedis.json
- clients/nodejs/github.com/redis/node-redis.json
- clients/python/github.com/redis/redis-py.json
- resources/clients/index.md
"Official" clients are now marked as `official: true` instead of `recommended: true`.
This PR is dependent on [this PR](https://github.com/redis-stack/redis-stack-website/pull/113).
> DOC-2511: reorder the clients by language list

- docs/data-types/strings.md
The string value is parsed into integer and incremented by one by the `INCR` command not the `INCRBY`.  `INCRBY` command increments the value with a given value not by 1 automatically. It increments the value by one if only it is explicitly told : `incrby total_crashes 1`
> Update strings.md , wrong command description

- docs/data-types/probabilistic/hyperloglogs.md
added a pfmerge example - condensed to one more robust example
> Update hyperloglogs.md with hugo short codes

- commands/memory-stats.md
the percentage is the total (current) out of peak (higher), not the other way around.
> fix swapped vars in memory-stats, and minor wording

- docs/data-types/streams.md
The examples don't mention apples, strawberries or oranges, so let's change the text to match the examples.
> fix inconsistency in streams docs

- docs/install/install-redis/_index.md
> Fixed some broken links

- resp2_replies.json
- resp3_replies.json
The WITHSCORE option was referenced as WITHSCORES (plural)
> Update ZRANK WITHSCORE reference in resp2 & resp3_replies.json

- commands/hrandfield.md
- commands/hstrlen.md
[HMSET](https://redis.io/commands/hmset/) is deprecated as of Redis 4.0.0, and [HSET ](https://redis.io/commands/hset/) is the prefered method for this interaction. This PR updates the examples where we were refering to the deprecated command.
> Moving HMSET used by examples to HSET

- docs/reference/protocol-spec.md
In the protocol spec, the description of how maps are represented in RESP2 is incorrect.
"Maps in RESP2 are represented by arrays, in which each element is a key-value tuple. Each tuple is an array with two elements, these being the key and the value."
This is not true. A map in RESP2 is represented as a flat array containing the keys and values, not nested arrays.
> Correction of map representation in RESP2

- docs/connect/cli.md
It's good for users to know that they need to specify "default" as the username when authenticating without a username. Other details of the URI format are described too, like scheme and dbnum.
It used to be possible to connect to Redis using an URL with an empty username, like redis-cli -u redis://:PASSWORD@localhost:6379/0. This was broken in 6.2 (https://github.com/redis/redis/pull/8048), and there was a discussion about it https://github.com/redis/redis/issues/9186. 
Now, users need to specify "default" as the username and it's better to document it.
Refer to https://github.com/redis/redis/issues/12746 and #2523 for more details.
> Add an explanation for URI with -u in redis-cli

- docs/management/admin.md
getting-started/faq redirects to get-started/faq. As a result, this link is not fully functional (the part after the hashtag is lost after redirection):
https://redis.io/docs/getting-started/faq/#background-saving-fails-with-a-fork-error-on-linux
> Update getting-started/faq to get-started/faq

- docs/management/scaling.md
`redis-cli --cluster del-node` doesn't work since it tries to connect to all nodes. `--cluster call CLUSTER FORGET` works though.
> Explain how to remove failed cluster node (#2427)

- docs/management/persistence.md
- wordlist
As discussed in https://github.com/redis/redis/issues/12484, here is a suggestion for improved AOF conversion documentation.
The first commit just adds a simple warning. In the second commit, I removed the section for Redis <2.2, which is out of support for a long time now. (If I'm not mistaken, 2.2 was released in 2011.)
I can also squash the two commits at request.
> Improve RDB to AOF conversion docs

- docs/install/install-redis/_index.md
> add link and fix a bit of language to address issue #885

- commands/acl-dryrun.md
In redis/redis#10405, we will check arity first, so the example
output is wrong. And in redis/redis#11160, we changed the text.
```
127.0.0.1:6379> ACL DRYRUN VIRGINIA GET foo bar
(error) ERR wrong number of arguments for 'get' command
127.0.0.1:6379> ACL DRYRUN VIRGINIA GET foo
"User VIRGINIA has no permissions to run the 'get' command"
```
> Fix incorrect output of example in ACL DRYRUN

- commands/set.md
Clarify that argument is a positive integer, unlike EXPIRE which accepts zero and negative numbers too.
> SET options EX, PX, EXAT, PXAT take positive integer argument

- commands/info.md
Info fields from the rearrangement of scripts when functions were introduced.
see https://github.com/redis/redis/pull/9780
> Add some missing INFO fields about FUNCTION

- commands/function-delete.md
The command format is using the old one and it is outdated.
> Fix outdated incorrect example in function delete

- commands/memory-stats.md
see redis/redis#12897, the computing method has changed for bytes-per-key.
> Update keys.bytes-per-key's description.

- docs/reference/cluster-spec.md
Adding to the cluster spec documentation of the following Redis features:
redis/redis#12754 (SCAN)
redis/redis#12536 (KEYS)
redis/redis#12728 (SORT, SORT_RO)
Do we need to mention this in the manual for each of the commands?
Related to #2610.
> Explain patterns with hash tags in cluster spec

- docs/connect/clients/java.md
cc @dwdougherty @sazzad16 @chayim
> Add "Production usage" section to Jedis quick start

- commands/info.md
In redis/redis#12476 two new info merics are added: `client_query_buffer_limit_reached` and `client_output_buffer_limit_reached`.
Also correct the info of `reply_buffer_shrinks` and `reply_buffer_expands`.
> Update info docs with two buffer limit metrics.

- commands/function-dump.md
The old example uses an old format, which is no longer supported,
it will return an `ERR Pre-GA function format not supported` error.
Also the FUNCTRION LIST example is also a bit outdated.
> Fix FUNCTION DUMP outupdated examples

- commands/info.md
- commands/memory-stats.md
The corresponding doc PR of https://github.com/redis/redis/pull/12913
> Add overhead metrics to info and memory stats.

- commands/sort.md
> Allow by/get of sort(ro) in cluster mode.

- commands/client-list.md
- commands/info.md
Doc of https://github.com/redis/redis/pull/12966
> Add WATCH metrics

- commands/object-encoding.md
> Update object-encoding doc to mention all the encodings

- commands/keys.md
- commands/scan.md
As the optimization done in redis/redis#12754, we may doc this in the command page.
> Update KEYS and SCAN page with new optimization about pattern with hash tag.

- resp2_replies.json
- resp3_replies.json
On https://redis.io/commands/info/ at the bottom, the RESP documentation renders like this:
Notice the
>in the form of : where
and
>separated map like =.
and
>terminated by .
> Fix the rendering of the RESP documentation for the INFO command

- commands/xinfo-consumers.md
- commands/xinfo-stream.md
Document all the information returned by XINFO STREAM FULL
Also, document the behavioral change of consumer seen-time/idle since 7.2.0
Fixes #2230
> Document XINFO STREAM FULL

- clients/ballerina/github.com/redis/ballerinax-redis.json
This PR adds information on the Official Redis client library for [Ballerina](https://ballerina.io/). This client comes with the support for Redis clusters, connection pooling and secure connections OOTB.
- Ballerina Redis Client Package: https://central.ballerina.io/ballerinax/redis/latest
- Source Repository: https://github.com/ballerina-platform/module-ballerinax-redis
- Client Specification Documentation: https://github.com/ballerina-platform/module-ballerinax-redis/blob/master/docs/spec/spec.md
- Ballerina Programming Language Homepage: https://ballerina.io/
> Add Ballerina Redis client

- clients/perl/github.com/plainbanana/Redis-Cluster-Fast.json
[Redis::Cluster::Fast](https://github.com/plainbanana/Redis-Cluster-Fast) is a Perl XS module to connect Redis Cluster by hiredis-cluster and hiredis.
Implementing and maintaining a Redis Cluster client correctly, especially with error handling, is quite complex and difficult.  By leveraging the async cluster context of hiredis-cluster, it allows us to update the cluster topology as needed while processing commands.
> Add Redis::Cluster::Fast client

- commands/eval.md
- commands/info.md
see https://github.com/redis/redis/pull/13108
> Add new INFO evicted_scripts field and eval scripts eviction

- docs/connect/clients/java/_index.md
- docs/connect/clients/java/java.md
- docs/connect/clients/java/lettuce.md
Created new Java "folder" under Connect > Clients, and moved the Jedis and Lettuce guides under it.
@mich-elle-luna Igor would like this merged today at some point, so please review and approve.
> DOC-3547: gather Java clients under Java 'folder'

- docs/connect/clients/java/_index.md
- docs/connect/clients/java/jedis.md
This PR corrects the Connect > Clients > Java section.
@dmaier-redislabs or @mich-elle-luna Please review ASAP so I can get it merged.
> DOC-3564: fix Java client menu
