redis/redis-doc

tools.json
Hi,
Here is a new GUI client for Redis based on hiredis
Thanks
=> FastoRedis client

commands.json, commands/restore.md
`REPLACE` modifier added by https://github.com/antirez/redis/commit/e5b5763f56d1379069c94ce7196c1a412bb44fba
=> Add REPLACE modifier to RESTORE's documentation

clients.json
Hey guys,
We have moved the phpredis repository in preparation for the next PECL release as well as the soon to be released cluster support.  This change just reflects the new location as well as adds me to the list of authors.
Cheers,
Mike
=> Update phpredis location and authors

tools.json
While looking through the tools, I thought I'd fix some of the broken/moved urls.
=> Added a couple tools, fixed some urls

topics/faq.md
=> Spelling/typo in faq.md

commands.json, commands/spop.md
Relevant redis pull request:
https://github.com/antirez/redis/pull/1803
=> Updated SPOP documentation, following redis issue #1793: SPOP optional count argument

commands/expire.md, topics/latency.md
=> Fix number of keys sampled per expire loop (issue #461)

topics/distlock.md
As subject, added reference to C#/.NET implementation of Redlock.
=> Added C# implementation

commands/sunionstore.md
Related to https://github.com/antirez/redis-doc/pull/194#discussion_r20196196
=> Fix command name in sunionstore.md

topics/cluster-tutorial.md
It is currently in active development and working on second release.
=> Update redis-py-cluster in cluster-tutorial

topics/cluster-tutorial.md
because i spent 3 days trying to make 2.8 work like a cluster
=> Adding a note a the beginning saying that version 3.0 is required

clients.json
[thunk-redis](https://github.com/thunks/thunk-redis)
==========
A redis client with pipelining, rely on thunks, support promise. 
+ beautiful code style
+ pure javascript code(Javascript RESP parser)
+ full and high-level test(`npm test`)
+ a little faster than node_redis(hiredis parser)(`node benchmark/index`)
I hope you can recommend it :100: 
**default thunk API:**
```js
var redis = require('thunk-redis');
var client = redis.createClient({
database: 0
});
client.on('connect', function() {
console.log('redis connected!');
});
client.info('server')(function(error, res) {
console.log('redis server info:', res);
return this.dbsize();
})(function(error, res) {
console.log('surrent database size:', res);
return this.select(0);
})(function(error, res) {
console.log('select database 0:', res); …
```
=> add Node.js  redis client: thunk-redis.

clients.json
=> add a async redis client for php.

topics/persistence.md
Related: same typofix in .html doc https://github.com/datasaur/redis-dash/pull/1
=> Fixing typo in persistence doc

topics/replication.md
=> Add clarity to "partial synchronization"

topics/lru-cache.md
As far as I can see in the description of the allkeys-random policy we are talking about [Uniform distribution](http://en.wikipedia.org/wiki/Uniform_distribution_(continuous)), not about [Normal distribution](https://en.wikipedia.org/wiki/Normal_distribution)
=> Fix distribution for allkeys-random policy in lru-cache.md

topics/cluster-spec.md
=> Various typos in cluster-spec

clients.json
The project page : https://github.com/claus/as3redis is a 404
=> Remove action script client (as3redis)

topics/data-types-intro.md
=> Fix the command format in data-types-intro.md

topics/distlock.md
https://github.com/mike-marcacci/node-redlock
=> Added nodejs implementation to list

commands/eval.md
=> "Escaped" KEYS + formatted KEYS

tools.json
phpRedExpert ia simple and powerful web UI for Redis databases and servers management, written in PHP and JavaScript.
=> Add phpRedExpert tool to the docs

topics/cluster-tutorial.md
I created separate commits for each fix to make cherry-pick'ing easier if you don't want to merge all of changes.
=> Redis Cluster tutorial small fixes (typos and tenses)

commands/georadius.md
WITHHASH was mispelled as WITHASH
=> Copy edit for typo

topics/memory-optimization.md
Wordsmithing of this doc section.
=> Cleanup of the doc section: Bit and byte level operations.

topics/cluster-tutorial.md
=> Fix wrong word usage in context, s/slave/master/

tools.json
Please include Hibernate OGM in the tools listing
=> Add Hibernate OGM to the tools listing

clients.json
=> Consolidated clients update (closes 23 other pull requests)

clients.json
Add [uglide/qredisclient](https://github.com/uglide/qredisclient) to clients.json
=> Add qredisclient to clients.json

clients.json
@badboy I made a mistake in the ```author``` I thought it's a github username
=> Change vRedis twitter handle

commands/cluster-info.md, commands/cluster-setslot.md
Fix some typos in redis documentation.
=> fix some typos.

commands/eval.md
See https://github.com/antirez/redis/commit/30278061cc834b4073b004cb1a2bfb0f195734f7#diff-792ebfd4581312e7344b1e48adad7f10R633
=> debug library no longer available

topics/indexes.md
=> Typo in indexes.md

clients.json
* Add recommended flag (ok with you?)
* Add url
* Changed description
=> Update lettuce client

topics/distlock.md
Add a link to RedLock.net C#/.NET distlock implementation
=> Add RedLock.net to distlock implementation list

topics/pubsub.md
=> List of commands allowed for subscriber

commands/expire.md
=> Clarify which events clear EXPIRE timeout

clients.json
=> Add mruby redis client to list

clients.json
=> Update twitter account of mruby redis client

tools.json
=> Added hollodotme/readis

commands.json
=> Add SCRIPT DEBUG

clients.json
=> remove wrong twitter account

topics/sentinel.md
Thanks for the great documentation, it has been very helpful to me.
=> fix sentinel ascii art box alignment

topics/notifications.md
Dependent on the merging of https://github.com/antirez/redis/pull/3059
=> Adds notification for `LREM` operations

topics/twitter-clone.md
Some minor grammar mistakes.
Great tutorial, thanks!
=> Fix a couple small grammar mistake in twitter clone tutorial

clients.json
A c++ redis client supports cluster/pipeline, and will support transaction soon.
=> add a c++ redis client

clients.json
A new Swift client, written in pure Swift without Foundation dependencies.
=> Add Swift-Redis client

clients.json
I'm surprised this package isn't already in the list, but I didn't see it. It is fairly popular.
=> Update client.json with go-redis/redis client

commands.json
=> Added parameter message for PING command

topics/rediscli.md
Great addition - sorry for all the formatting changes.
=> Edits and such

topics/benchmarks.md
Before this PR is merged,  antirez/redis#3164 needs to be merged.
=> Fix typo topics/benchmarks

commands.json
=> Fixed STORE and STOREDIST params for GEORADIUS and GEORADIUSBYMEMBER

commands.json, commands/geoadd.md
The commands should not show up as beta anymore.
Also simplified the GEODEL note.
=> Added version info for GEO* commands

clients.json
cpp_redis has been modified a lot and the description of the library was completely out of date.
=> update cpp_redis description

topics/transactions.md
As per #734 WATCH accounts for modifications by its own connection
=> Clarified when WATCH doesn't abort EXEC

clients.json
https://github.com/jamespedwards42/jedipus
=> Add Redis Cluster Java Client, Jedipus.

topics/sentinel.md
Re-reading the Sentinel doc, I found a few minor issues. Nothing changing semantics.
=> Sentinel updates

clients.json
=> add hiredis-vip client for redis cluster

commands/eval.md
Ref commits:
https://github.com/antirez/redis-doc/commit/ab172df2f66176bc00bc3996c2b95bd830d3d156
https://github.com/antirez/redis-doc/commit/b262a108614e6d526ead0b5cf9a00f70d1bc237a
=> Missed commit for delete Redis 3.2 currently not stable

commands/expire.md
https://github.com/antirez/redis-doc/issues/491
=> Fix active/passive terminology in EXPIRE docs, fixes #491

commands/slaveof.md
Changes: "that would" -> "which would"; "remember you about" -> "remind you that"; "but something" -> "and something".
=> reword slavery note for grammar

topics/indexes.md
=> Fixing grammatical error

topics/faq.md
At least this is how I've read its pronounced.
=> Added pronunciation

tools.json
I have started working on a python, qt based GUI for redis.
In development state but already pretty much usable
=> Add QRedis

clients.json
Redis Client for mruby with Async support, pipelines and transactions
=> Add mruby-hiredis

modules.json
Specifically:
* RediSearch
* Redis-ML
* ReJSON
=> Adds some Redis modules

topics/problems.md
👋 Hey Salvatore!
I'm working at Librato and noticed that this link was hitting an old sub-domain. This fix sends it to the right place.  
Hope your well, hopefully I'll get  to see you at Redis Conf.
=> Update 10.04 warning

clients.json
=> remove scala-redis-client

tools.json
Hope it's ok to add a paid app to the list, I noticed a couple others in there so I assume it is.
Thanks!
Martin
=> add Regis to the list of higher-level tools

clients.json
=> add bredis (c++ client)

topics/twitter-clone.md
=> Fix typos in twitter-clone topic

clients.json
update r3c introduction, add support password
=> update r3c introduction, add support password

clients.json
An async redis library for C++ based on libevpp/boost-asio
https://github.com/hamidr/async-redis
=> Add async-redis to c++ clients

clients.json
Please add gxredis to clients list, thanks.
=> Add gxredis for language Python

topics/notifications.md
=> Fixes minor typo

modules.json
https://github.com/kristoff-it/redis-cuckoofilter
=> add kristoff-it/redis-cuckoofilter to modules.json

commands/keys.md
In order to reduce confusion between values and keys and _key index_ we replace example with one and 1 (and _1)_) with name, age and some stuff around people.
=> Improve keys examples

clients.json
Hi @antirez, please accept the PR,  my twitter nick was changed, the old one is pointing to someone else. Thanks
=> erroneous twitter account for spade client

commands/object.md
Introduced with v4's LFU maxmemory policies.
=> Adds the `OBJECT FREQ` subcommand

topics/rediscli.md
This should be merged if and when https://github.com/antirez/redis/pull/3409 is merged upstream.
=> Documents the `-u <uri>` option

modules.json
With this PR I wish to add the module to the documentation.
Thanks,
Simone
=> Add rediSQL

commands/scan.md
Changed `an hint` to `a hint`.
=> Minor typo correction

topics/data-types-intro.md
=> fix a small typo

clients.json
Updating Jedis Client Description in client.json
=> Updating Jedis Client Description in client.json

tools.json
Redis Browser is a Cross platform GUI tool for redis, that includes support for displaying json stored in redis through the redis rejson plugin
=> Adding redis-browser to tools section

commands/georadius.md
`s/GEORADIUSBYRANGE_RO/GEORADIUSBYMEMBER_RO/`
=> fix mention of georadiusbymember_ro command

commands.json, commands/bzpopmax.md, commands/bzpopmin.md, commands/zpopmax.md, commands/zpopmin.md
This adds the documentation pages and updates commands.json per https://github.com/antirez/redis/pull/4879.
Should be merged upon releasing v5 (assuming that this will be included in it ;))
=> Documents [B]ZPOP<MIN|MAX>

commands/xadd.md, commands/xlen.md, commands/xrange.md, commands/xread.md, topics/streams-intro.md
=> Misc edits to streams docs

modules.json
Ref: https://redislabs.com/community/redis-modules-hub/
=> Fix license of Redis Labs modules

commands/zpopmax.md, commands/zpopmin.md
Update command description to reflect this change https://github.com/antirez/redis/commit/0a698e499a0b543b350544c63701ab944151c6ed
=> Swap ZPOP pair order

commands.json, commands/client-list.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Add TYPE filter and description of name field to CLIENT LIST

commands.json, commands/xreadgroup.md, topics/streams-intro.md
Fixes https://github.com/antirez/redis/issues/5494 as well as couple of typos in streams-intro.
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Adds NOACK to XREADGROUP

modules.json
Updating the license, creators and the correct github link
=> Updating RedisGraph in modules.json

topics/data-types-intro.md
Added a reference to the Streams Intro, and an exception to the rule of empty aggregate data types.
=> Adds Streams to data types intro

commands/zrangebylex.md, commands/zrangebyscore.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Documents negative count for ZRANGEBYSCORE/LEX LIMIT

commands.json, commands/restore.md
Due to commit b5197f1fc9d6fde776168951094e44d5e8742a89
in the Redis repo.
=> Updated RESTORE docs

topics/replication.md
=> Losign --> Losing typo fix in Replication doc

commands.json, commands/migrate.md
Fixes #1127 
Do I also add a small paragraphe, with an exemple on how to use the option?
=> Add doc for MIGRATE's AUTH option

commands/bitfield.md
Make the example command match the explanation.
=> Fix mistake in bitfield.md

clients.json
Added Redis Cluster client Redis::ClusterRider for Perl
=> Added Redis Cluster client Redis::ClusterRider for Perl

topics/twitter-clone.md
I just read the article contained in the file `twitter-clone.md`. Thank you for writing this nice introduction. I found some inconsistencies while reading and propose to make some format changes.
While most variable names and commands are highlighted using backticks, few of them are also wrapped in asterisks or single quotes. I propose to adjust the format to be more consistent to make the article easier to read.
=> Make the format of variable names more consistent

commands/select.md
I had trouble understanding the docs for `SELECT`, so I thought I'd attempt to clean it up. I wasn't trying to change it substantially, hopefully I got the gist.
=> Update select docs

commands/subscribe.md
Adds the previously-undocumented `PING` and `QUIT`.
=> Updates allowed commands in SUBSCRIBE

commands/set.md
I had trouble finding the correct way of setting a key with an expiration date with the current documentation (maybe because of #928 / #973)
So I though adding an example would be nice for new users
=> Add example for SET command with expiration

commands/info.md, commands/memory-stats.md
As per https://github.com/antirez/redis/pull/4883
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Adds Lua metrics to INFO and MEMORY STATS

topics/pipelining.md
Image was http, should be https
=> Fix mixed content warning on pipelining

clients.json
=> Added dartis to clients.json

clients.json
=> Revert "Adds warlus to clients.json"

topics/distlock.md
add distlock csharp implementation repertory
=> add distlock csharp implementation repertory

clients.json
Add laserdisc scala client - https://github.com/laserdisc-io/laserdisc
=> Add the laserdisc scala client

commands.json, commands/psync.md, commands/sync.md
Fixes #939 
@mingrammer - I appreciate #940 but after some editing and corrections it turned into this. Please let me know if this makes sense to you.
@stockholmux @@bmansheim please help with a review.
=> Adds minimal references to SYNC and PSYNC

commands/flushall.md
As suggested in https://github.com/antirez/redis-io/issues/163#issuecomment-447572197
=> Specify behavior of flushall async on new keys

commands.json, commands/xread.md
This PR addresses the issues noted in this issue: https://github.com/antirez/redis/issues/5750
as well as a couple more that were noticed while preparing the changes.
=> Address typo / legibility issues

topics/cluster-tutorial.md
ioredis supports Redis Cluster out of the box: https://github.com/luin/ioredis#cluster. 🍺
=> Add introduction to ioredis

commands/xreadgroup.md
=>  XREADGROUP ignores BLOCK and NOACK

topics/data-types-intro.md
=> Minor: move space

topics/indexes.md
At least this line contradicts line 26
Which is it? Float or integer?
=> Sorted set score is double-precision float

topics/acl.md
Adding documentation for adding hashes to the ACL topic.
=> Adding Hashes to ACL Topic.

modules.json
I guess I had to add my github username as author field.
Related to https://github.com/antirez/redis-doc/pull/998
Thanks
=> update lqrm author

commands/setbit.md
@stockholmux @bmansheim I'd appreciate a once over.
=> Adds access patterns to bitmaps

commands/scan.md
=> Adds version history for SCAN TYPE

commands.json, commands/cluster-bumpepoch.md, commands/cluster-flushslots.md, commands/cluster-myid.md
=> Adds `CLUSTER`'s `BUMBEPOCH`, `FLUSHSLOTS` and `MYID`

commands.json
This would probably be better handled by the website's implementation, but until then... (https://github.com/antirez/redis-io/issues/186)
=> Sorts commands.json alphabetically (as redis.io doesn't)

commands.json
unique index parameters index1, index2 SWAPDB like member1, member2 GEODIST
=> update commands.json: unique index parameters SWAPDB

topics/sentinel.md
=> Adds a couple of hyphens

commands/xgroup.md, topics/streams-intro.md
`MKSTREAM` was added to Streams, but there is no documentation on it yet.
See #1007
=> Update docs to include MKSTREAM usage

tools.json
- lightweight
- no PHP redis module required
- connection via IP/port or socket
- password support (including Redis 6 ACLs)
- show details
- flush database (async support)
- flush instance (async support)
- command mapping support (when rename-command is used on the server)
- auto refresh
=> add redis-stats to tools.json

commands.json
GEODIST - change unit type from string to enum like GEORADIUS, GEORADIUSBYMEMBER
=> update commands.json GEODIST: change unit type to enum

topics/memory-optimization.md
See https://github.com/antirez/redis/commit/02bb515a094c081fcbc3e33c60a5dbff440eb447
=> Multiple list encoding options no longer supported.

topics/faq.md
This small pull request tidies up the phrasing in the FAQ page a little bit.
=> A few improvements to the phrasing in the FAQ.

modules.json
as suggested by https://github.com/poga/redis-percentile/issues/2
=> add redis-percentile module

commands.json
Change client-id in CLIENT UNBLOCK to type integer as command CLIENT ID returns an integer.
=> update commands.json CLIENT UNBLOCK: change client-id type to integer

topics/internals-vm.md
1. Fix the typo error in `topics/internals-vm.md`, in line 230, main thread delegates tasks and the execution should be handled by I/O thread.
2. Add markdown code wrapper for variables whose name contains `_`, or words like `REDIS_VM_MEMORY` will be represented in _italic_.
=> fix(vm): fix typo error in vm-intro and beautify styles

modules.json
- Added Disque and RedisGears module info. 
- Updated some modules remote endpoints. 
- Updated module stars.
=> [add] added Disque and RedisGears module info. Updated module stars.

tools.json
In order to add my Redis tool  "Lua Redis Admin"
=> append tool with Lua Redis Admin

modules.json
redis-protobuf is a Redis module for reading and writing Protobuf messages.
=> Update modules.json: add redis-protobuf module

clients.json
Added viredis to the list of java clients.
viredis- A simple and small java client to talk with redis
=> Adds viredis to the java clients

modules.json
=> add reventis entry to modules.json file

topics/modules-intro.md
=> Fixes the example of simplest module to compile

commands/xrange.md, commands/xread.md, commands/xrevrange.md
Looks like the name was typo'ed when first introduced.
https://en.wikipedia.org/wiki/Toni_Morrison
=> Fix author name in docs.

topics/data-types-intro.md
A couple of minor grammar improvements
=> Improve grammar

topics/data-types.md
* leader board --> leaderboard
* an user --> a user
=> Fix typos in Sorted set section

clients.json
Removing "Active" status for predis, since it has no commits in almost 3 years
=> Update active status of predis in clients.json

commands.json, commands/bgsave.md
* Add details about situations where BGSAVE returns errors
* Describe the SCHEDULE option introduced in 3.2.2
=> Document BGSAVE SCHEDULE

topics/notifications.md
Upstream: https://github.com/antirez/redis/pull/6976
=> Adds migrate and restore to keyspace notifications

topics/indexes.md
=> Fix URL link to Hexastore paper

commands/stralgo.md
Hi, was reading the doc for stralgo and I noticed a couple typos. I did not do syntax changes as I am not a native EN speaker. 
Thanks
=> Couple typo fix

topics/notifications.md
add persist event notification based on recent fix: https://github.com/antirez/redis/pull/7039
=> add persist event notification

commands/bgsave.md
```
127.0.0.1:6379> bgsave
Background saving started
```
=> bugfix: fix reply message for bgsave.

commands/acl-cat.md, commands/auth.md, commands/hello.md, commands/stralgo.md
Some small typo corrections in the command docs.
=> Minor typo corrections

topics/security.md
This sentence makes less sense with all of the new security features in Redis 6.0.
=> Remove misleading statement about security

clients.json
https://redis4cats.profunktor.dev/
=> Add Redis4Cats Scala client

commands.json, commands/acl-getuser.md, commands/acl-help.md
=> Adds ACL's `GETUSER` and `HELP`

commands/client-kill.md
=> Fixes #1313

tools.json
River is a library built on top of Redis Streams written in C++ and with
Python bindings. It's not a client per-say but rather a useful framework
that people can use for a more tailored interface to Redis Streams for
both streaming and persistence.
=> Adding river to C++ and Python Redis clients

commands.json
LATENCY HELP commands says:
```
127.0.0.1:6379> latency help
6) RESET   [event ...] -- Resets latency data of one or more event classes.
7)                        (default: reset all data for all event classes)
```
=> latency reset's args cloud be multiple.

topics/streams-intro.md
Following the replication documentation jargon
=> Use replica in stream documentation

commands/object.md
more infomation can be found at https://github.com/antirez/redis/issues/5182
=> correct the documents for object idletime

modules.json
Audio Track Recognition comes to Redis.  
https://github.com/starkdg/Redis-AudioScout
=> add redis-audioscout and bump up no. stars on reventis

topics/acl.md
there is no readonly command category but read
=> ACL Command Category from @READONLY to @READ

topics/replication.md
Replaces PR #953 
@itamarhaber Great job on cleaning up the docs!
=> Fix small typos and grammar in replication

commands/georadius.md
=> Fixes #1267

clients.json
https://github.com/redis/redis-io/issues/203
=> Outdated Redis PHP Clients

topics/modules-api-ref.md
=> Update Module API reference.

clients.json
Added the _Redis COM client_ wrapper for COM environments like classic ASP.
=> Added Redis-COM-client to redis.io/clients

commands/info.md
https://github.com/redis/redis/pull/7446
=> Show theading configuration in INFO output

clients.json
Adding a new Rediska client to clients.json list.
=> adds Rediska to clients.json

topics/cluster-tutorial.md
Added directive that was missing from example command.
=> Fix missing directive

topics/modules-intro.md
This is the documentation corresponding to the Module OnUnload hook in pull request:  https://github.com/antirez/redis/pull/5926
=> Documentation for Module OnUnload hook

modules.json
=> Update modules.json to add redis_hnsw

topics/notifications.md
=> Adds a note about cluster keyspace notifications

commands.json, commands/zmscore.md
Docs PR for https://github.com/redis/redis/pull/7593 , which is still in review
=> Add documentation for zmscore command

commands.json, commands/zinter.md, commands/zunion.md
see: https://github.com/redis/redis/pull/7794
=> Add `ZINTER/ZUNION` command

topics/rediscli.md
https://redis.io/topics/rediscli
in topic rediscli chapter, "TThere" Spelling mistakes
"TThere" -> There
=> Fix document spelling errors

commands.json, commands/blpop.md, commands/brpop.md, commands/brpoplpush.md, commands/bzpopmax.md, commands/bzpopmin.md
WRT https://github.com/redis/redis-doc/pull/1347#discussion_r500768125
=> Uses double timeout value in blocking commands

commands.json, commands/monitor.md, commands/reset.md, commands/subscribe.md
Ref: https://github.com/redis/redis/pull/7982
Missing the 'Time complexity' which could be O(N+M+Q+P+...) though.
=> Adds the RESET command

commands/info.md
Ref: https://github.com/redis/redis/pull/7981
Ref: https://github.com/redis/redis/pull/7979
=> Updates INFO fields about diskless loading progress and maxclients

clients.json
The high-performance redis client supports .NETCORE/.NET4.0/.NET4.5, which is specially optimized for big data and message queuing. The average daily call volume of single online application is 10 billion
=> The high-performance redis client supports .NETCORE/.NET4.0/.NET4.5

topics/streams-intro.md
Finished going over all of the streams doc. This includes all my fixes.
=> more stream doc cleanups

commands.json, commands/copy.md, topics/notifications.md
Ref: https://github.com/redis/redis/pull/7953
=> Adds the COPY command

commands/acl-getuser.md, commands/acl-list.md, commands/acl-setuser.md, topics/acl.md, topics/sentinel.md
Ref: https://github.com/redis/redis/pull/7993
=> Documents ACL Pub/Sub

commands/xrange.md, commands/xrevrange.md, topics/streams-intro.md
See https://github.com/redis/redis/pull/8072
Also simplifies iteration examples as a result.
=> Adds exclusive ranges to XRANGE/XREVRANGE

commands.json, commands/client-info.md, commands/client-list.md
Ref: https://github.com/redis/redis/pull/8113
=> Adds CLIENT INFO and CLIENT LIST ID

commands/xpending.md
Ref: https://github.com/redis/redis/pull/8130
=> Documents XPENDING's exclusive ranges

commands/info.md
=> Add description for total_forks in INFO STATS

commands.json, commands/geosearch.md, commands/geosearchstore.md, wordlist
refer https://github.com/redis/redis/pull/8094
=> Add GEOSEARCH/GEOSEARCHSTORE command doc and explain geo search process

topics/cluster-tutorial.md, topics/rediscli.md
Specifically `REDISCLI_CLUSTER_YES` and `REDISCLI_RCFILE`
Ref: https://github.com/redis/redis/issues/8028
=> Documents '--cluster-yes' and a couple of env vars

commands.json, commands/lpop.md, commands/rpop.md, commands/spop.md
Also edits SPOP.
Ref: https://github.com/redis/redis/pull/8179
=> Adds count to L/RPOP

commands.json, commands/client-trackinginfo.md
Ref: https://github.com/redis/redis/pull/7309
=> Documents CLIENT TRACKINGINFO

commands.json, commands/hello.md
Ref: https://github.com/redis/redis/pull/7377
=> Documents noargs HELLO variant

commands.json, commands/geoadd.md, commands/zadd.md
geoadd command add CH/NX/XX option
=> geoadd command add CH/NX/XX option

clients.json
as of 0.14.0 hedis supports cluster. See: https://github.com/informatikr/hedis/blob/master/CHANGELOG
=> hedis now supports cluster

commands/info.md
Add a description for the new current_cow_size field in INFO
Ref: https://github.com/redis/redis/pull/8264
=> update INFO doc for current_cow_size field

commands.json, commands/client-pause.md, commands/client-unpause.md, wordlist
Documentation for PR: https://github.com/redis/redis/pull/8170
=> Documention for client pause

commands/set.md
=> update three to four

topics/modules-api-ref.md
This is cleanup down in:
https://github.com/redis/redis/pull/8325
=> update module api formatting and missing functions

topics/modules-api-ref.md
See https://github.com/redis/redis/pull/8344
=> Apply module command cleanup from redis/8344

commands/incr.md
Addressed in Issue - (https://github.com/redis/redis-doc/issues/1300) #1300
=> Fix: Removed tonumber from the Lua script

commands.json, commands/getdel.md, commands/getex.md, commands/set.md
Documentation changes corresponding to https://github.com/redis/redis/pull/8327.
=> GETEX, GETDEL and SET PXAT/EXAT Documentation

commands.json, commands/flushall.md, commands/flushdb.md, commands/script-flush.md, wordlist
for: https://github.com/redis/redis/pull/8258
=> Update lazyfree-lazy-user-flush doc

topics/sentinel.md
* SENTINEL CONFIG GET
* SENTINEL CONFIG SET
* Host name support
=> Updates for Sentinel in 6.2.

commands/getdel.md
I feel this is needed since it says that it deletes the key (but it doesn't always do so).
maybe the part about the error return is excessive (we don't normally state that)
=> improve GETDEL description

topics/releases.md
Note to self/any: a similar edit is needed for the download page's header where versioning is explained.
=> Revamps release process description

clients.json
* Removes some suspended/wrong Twitter accounts
* Removes jedipus as it no longer exists
* Removes Hierdis as it no longer exists
=> Cleans clients.json

tools.json
* Removes redis-mount as it no longer exists
* Fixes some twitter accounts and removes suspended
* Fixes description of redis_builder
=> Updates tools.json

topics/persistence.md
As per common convention: explain the meaning of an acronym the first time it is introduced.
I couldn't find the definitions of RDB and AOF and had to google for it. This will make the page more easy to follow for newcomers.
=> Persistence: Define acronyms RDB and AOF

topics/partitioning.md
Jedis has `ShardedJedis` and `ShardedJedisPool` for client side partitioning.
=> Added Jedis as an example of client side partitioning

commands.json
=> Fix GEOPOS time complexity

commands/eval.md
Add documentation for Lua behavior under low memory conditions, namely around ways that Lua can cause Redis maxmemory to be exceeded, and how to mitigate this.
=> Add documentation for Lua behavior under low memory conditions

topics/indexes.md
Fix LIMIT index error in ZRANGEBYLEX command of indexes.md.
Additionally fix one item in ZRANGEBYLEX output which should
not exist.
Fix https://github.com/redis/redis/issues/8738
=> Fix LIMIT index error in ZRANGEBYLEX command of indexes.md.

commands.json
Addresses https://github.com/redis/redis/issues/3015
=> Updated complexity of BRPOP and BLPOP commands.

commands/spop.md
Related code: https://github.com/redis/redis/blob/f5235b2d7660b163c739325ec9284f97d5b963be/src/t_set.c#L465-L466
=> SPOP with COUNT returns empty list (not nil)

commands/xadd.md
#This commit is related to the issue opened - (https://github.com/redis/redis-doc/issues/1332) | #1332
=> Feat: Added what happens when xadd fails

commands/slowlog.md
ref: https://github.com/redis/redis/pull/9018
Check the text and make sure i do it right.
btw, should we mention the redis-version?
=> slowlog get command supports passing in -1 to get all logs.

commands/getset.md
Fixes: https://github.com/redis/redis-io/issues/238
=> Add note re TTL getting reset by getset

modules.json
Add the redis-interval-module repository in modules.json
=> Add redis-interval-module

clients.json
Removing Erlang clients that are not maintained in the last 5 years.
=> Cleanup erlang clients that are not maintained

topics/transactions.md
Clarifying transaction documentation after we fixed the expire bug.
=> Improve wording around expire + transact

topics/replication.md
I can't find any mention about this ignore on documentation. I found this issue, but nothing besides that: https://github.com/redis/redis/issues/1875
=> Update the doc about maxmemory on replicas

commands.json
BITPOS key bit [start [end]] instead of BITPOS key bit [start] [end].
=> Change args of BITPOS from [start] [end] to [start [end]]

commands/info.md
Add `process_supervised` description (and examples).
=> Add `process_supervised` description at INFO

commands.json, commands/expire.md, commands/expireat.md, commands/pexpire.md, commands/pexpireat.md
Doc changes for feature https://github.com/redis/redis/pull/2795
=> Add doc for new options of expire commands

topics/sentinel.md
=> Add missing hyperlinks to different sections of the sentinel doc

topics/sentinel.md
=> Sentinel: rephrase replica-priority paragraph.

commands.json, commands/blmpop.md, commands/lmpop.md
WIP: haven't tried local rendering, not sure about the output render.
I am also not very good at long sentences, not sure I have covered everything.
=> Add new LMPOP and BLMPOP commands.

topics/memory-optimization.md, topics/pipelining.md
👋 Hello
With this version of code it is easier to read
I used rubocop for analyze.
=> Formatted ruby examples

commands/info.md
https://github.com/redis/redis/pull/9377
=> Add info metrics total_active_defrag_time and current_active_defrag_time

commands/eval.md
Added:
* Big number reply format
* Verbatim String reply format
=> Update Lua RESP3 reply format

topics/memory-optimization.md
Removed work in progress updates soon section.
=> Minor tidy up and removed work in progress updates soon

commands.json, commands/client-no-evict.md, topics/clients.md
Document client-eviction mechanism
=> Client eviction

topics/rediscli.md
This PR fixes the typo mentioned in the title.
=> Typo: replcia --> replica

clients.json
Please add dedis to Dart clients.
thank you.
=> Add dedis to Dart client

commands.json, commands/bzmpop.md, commands/zmpop.md
https://github.com/redis/redis/pull/9484
=> Add new ZMPOP and BZMPOP commands.

commands.json, commands/blmpop.md, commands/lmpop.md
see https://github.com/redis/redis-doc/pull/1654#issuecomment-961894605
=> Remove optional flag in LMPOP/BLMPOP and remove BLMPOP examples

topics/modules-api-ref.md, topics/modules-intro.md
REDISMODULE_POSTPONED_ARRAY_LEN is deprecated
=> Replace REDISMODULE_POSTPONED_ARRAY_LEN with REDISMODULE_POSTPONED_LEN 

commands.json, commands/sintercard.md, commands/zintercard.md
https://github.com/redis/redis/pull/9425
=> Adds limit to SINTERCARD/ZINTERCARD.

commands.json
=> Adds some missing types to commands.json

commands.json, commands/bitcount.md, commands/bitpos.md
https://github.com/redis/redis/pull/9324
add additional argument BYTE|BIT to BITCOUNT and BITPOS
=> add additional argument BYTE|BIT to BITCOUNT and BITPOS

topics/rediscli.md
Waiting for https://github.com/redis/redis/pull/3758
And https://github.com/redis/redis/pull/3751
To be merged.
=> Interval for scan and bigkeys

commands.json, commands/bitfield.md, wordlist
And also uses string as its type
=> Renames BITFIELD's type to encoding

commands.json, commands/cluster-addslotsrange.md, commands/cluster-delslotsrange.md, topics/cluster-spec.md
Upstream: https://github.com/redis/redis/pull/9445
=> Update doc for new cluster command: CLUSTER DELSLOTSRANGE and CLUSTER ADDSLOTSRANGE

modules.json
Hi, i wanna add a new module (named tairzset) and update our previous Module information at the same time (they are tairhash and tairstring), thanks.
=> Add tairzset module information and update tairhash/tairstring stars.

topics/replication.md
Related to the discussion in redis/redis#9572.
=> Warnings and recommendations against writable replicas

clients.json
Hi, I made a RESP3 client library for golang. Could I put the link https://github.com/rueian/rueidis here? Thanks.
=> Add rueidis golang client lib

commands/info.md
Added in https://github.com/redis/redis/pull/9323
=> Add new async_loading field in INFO command

commands/xadd.md, topics/streams-intro.md
Upstream ref: https://github.com/redis/redis/pull/9217
=> Documents the <ms>-* form for XADD

commands.json, commands/config-set.md
Update `CONFIG SET` docs given https://github.com/redis/redis/pull/9748
=> Update for multiparam config set.

commands/info.md
Added in https://github.com/redis/redis/pull/8015
=> Add rdb_last_load_keys_expired/rdb_last_load_keys_loaded fields in INFO

commands/info.md
Added in https://github.com/redis/redis/pull/8687
=> Add evicted_clients field in INFO

commands/info.md
Added in https://github.com/redis/redis/pull/8645
=> Add current_cow_size_age field in INFO command

clients.json
Add a new fpc redis client, it's a wrapper for hiredis and fully tested.
=> add: isyscore's fpc redis client

commands/info.md
Added in https://github.com/redis/redis/pull/9448
=> Add slave_read_repl_offset field to INFO command

commands/info.md
Added in https://github.com/redis/redis/pull/8653
=> Add replica_announced field to INFO command

commands.json, commands/config-get.md
See https://github.com/redis/redis/pull/9914
=> muliparameter config get

topics/data-types-intro.md
=> extra spaces correction in sadd example

commands.json, commands/info.md, commands/shutdown.md, topics/signals.md
Doc update for redis/redis#9872
=> Update SHUTDOWN and Signal Handling

topics/persistence.md
Upstream PR link: https://github.com/redis/redis/pull/9788
=> Add multi part aof information

commands/info.md
Added in https://github.com/redis/redis/pull/7912
=> Add lazyfreed_objects field in INFO

commands/info.md
Added in https://github.com/redis/redis/pull/7807
PS: the other changes doesn't break the blame log (look like)
> but it also can be removed
=> Add dump_payload_sanitizations field in INFO

topics/protocol.md
ref: https://github.com/antirez/RESP3/issues/48
=> Add RESP3 notice to protocol page

commands/cluster-slots.md, topics/cluster-spec.md, wordlist
Updated `CLUSTER SLOTS` and the cluster-spec documentation to be in line with changed from https://github.com/redis/redis/pull/9530.
=> Added clusterhostnames and define unknown endpoints

clients.json, tools.json
=> Added redli to list of clients

modules.json
Adding new redis-s2geo module.
=> Add redis-s2geo module.

clients.json
=> Add LettuceF client

commands.json, topics/modules-api-ref.md
```
$ src/redis-server &
$ utils/generate-commands-json.py  > ../redis-doc/commands.json 
$ ruby src/modules/gendoc.rb  > ../redis-doc/topics/modules-api-ref.md 
```
=> Update auto gen files

docs/clients.md, docs/project/governance.md, docs/reference/patterns/distributed-locks.md
This pull request updates the docs for governance, clients and distributed locks for the new system.
=> Updates docs for governance, clients and distributed locks

commands/expiretime.md, commands/pexpiretime.md
=> Add missing newline after reply

commands/acl-getuser.md
return nil when user does not exist
=> Update doc for acl getuser

commands/function-dump.md
=> Minor fixes in function-dump documentation

topics/lua-api.md
Added `redis.acl_check_cmd()` documentation.
See: https://github.com/redis/redis/pull/10220
=> Added `redis.acl_check_cmd()` documentation.

commands/command-docs.md
see https://github.com/redis/redis/pull/10252
also added a example? the output may be a bit long though
=> Now summary and since not always present in COMMAND DOCS

commands/command-docs.md
see https://github.com/redis/redis-doc/pull/1780#pullrequestreview-875078537
=> Merge the two lists of fields (always present and sometimes present)

commands/xautoclaim.md, commands/xclaim.md
xref: https://github.com/redis/redis/pull/10227
=> Adjust X[AUTO]CLAIM handling deleted entries

commands/spublish.md, commands/ssubscribe.md, commands/sunsubscribe.md
=> Fix incorrect link to Sharded Pubsub in SPUBLISH

topics/key-specs.md
Doc change for https://github.com/redis/redis/pull/10299
=> Updated documentation for not key

commands/cluster-setslot.md
=> Clarify the importance of CLUSTER SETSLOT NODE to dst before src

commands/cluster-shards.md, topics/cluster-spec.md, wordlist
Ref: https://github.com/redis/redis/pull/10293
=> Added cluster shard command documentation

commands/xinfo-groups.md
see https://github.com/redis/redis/issues/10415
=> Fix entries-read output in XINFO GROUPS

commands/memory-stats.md
https://github.com/redis/redis/pull/10302
=> Add cluster.links in MEMORY STATS

commands.json, topics/modules-api-ref.md
=> update commands.json and moduleapi ref for 7.0 RC3

commands/function-list.md, commands/function-load.md, topics/functions-intro.md, topics/lua-api.md
Update function docs according to recent changes on : https://github.com/redis/redis/pull/10500
=> Update function docs according to recent changes

topics/acl.md
we drop that support in https://github.com/redis/redis/pull/10147
=> Remove subcommand first-arg description

topics/eval-intro.md
fix a minor typo in script cache section
=> Fix typo in eval-intro.md

docs/manual/keyspace-notifications.md
Document the changes in https://github.com/redis/redis/pull/10512
=> Document 'new' keyevent

commands/ssubscribe.md, commands/sunsubscribe.md, docs/manual/programmability/eval-intro.md, docs/manual/programmability/functions-intro.md, docs/manual/programmability/lua-api.md, docs/manual/transactions.md
seems quite a few links are leading to an 404, specifically ones without absolute path, found them with grep and confirmed they're all broken. hope this will fix them.
=> try to solve dead links

tools/gui/github.com/luin/medis.json, wordlist
Hey there 👋
Just want to list Medis on the tools page so users can find and evaluate whether it fits they needs.
BTW I found that the instructions for building the website on README seem outdated so LMK if there is anything missing in this PR. Thanks for the great work as always ❤️.
=> Add Medis to the tools page

docs/reference/key-specs.md
See https://redis.io/commands/command/
=> The key spec is the 9th reply in `Command`

clients/smalltalk/github.com/Pharo-Redis/Pharo-Redis.json, clients/smalltalk/github.com/RediStick/RediStick.json, clients/smalltalk/github.com/SimpleRedisClient/SimpleRedisClient.json, clients/smalltalk/squeaksource.com/Redis.json, clients/smalltalk/squeaksource.com/Redis/Redis.json, clients/smalltalk/squeaksource.com/RedisBinaryClient/RedisBinaryClient.json
This PR adds repository urls to the most popular Redis clients for Smalltalk.
I've followed the guidelines. Please let me know if it needs any change to merge. 
Thank you!
=> Adds the most known clients for smalltalk at this time.

commands/xautoclaim.md
=> Update documentation for XAUTOCLAIM

README.md
The README has details about the old format of listing clients.
=> Update README about clients

commands/command.md, commands/eval_ro.md, commands/evalsha_ro.md, commands/fcall_ro.md, docs/manual/programmability/_index.md, docs/manual/programmability/lua-api.md
updating docs with regards to these issues:
* https://github.com/redis/redis/pull/10699
* https://github.com/redis/redis-doc/issues/1948
* https://github.com/redis/redis/pull/10744
=> script flags update

commands/info.md
update to https://github.com/redis/redis-doc/pull/1966, 
related redis issue: https://github.com/redis/redis/pull/10810
=> Add info fields about input/output network bytes during replication.

commands/xadd.md
Believe list describes stream entry better and is consistent with behaviour
=> XADD redis entry clarfication

docs/getting-started/installation/install-redis-on-linux.md, docs/getting-started/installation/install-redis-on-windows.md
=> Updates windows install to use packages.redis.io

libraries/go/github.com/hdt3213/godis.json
Add hdt3213/godis into libraries/go
=> Add hdt3213/godis into libraries/go

commands/object-encoding.md, wordlist
=> Add embstr description to Object Encoding command

commands/info.md
https://github.com/redis/redis/pull/10929
=> Add pubsubshard_channels field in INFO STATS

docs/manual/replication.md
Hello,
This pull request simply fixes a few typos.
Thanks for this really great documentation.
Have a nice day.
=> Fix a few typos

commands/lcs.md
It is better to add type display, also same as LCS IDX below
=> Add integer type to the return of LCS LEN

commands/client-list.md
https://github.com/redis/redis/pull/10895
=> Add ssub in CLIENT LIST

.spellcheck.yml
Implements option 4 of https://github.com/redis/redis-doc/pull/2038#issuecomment-1180579023
=> Excludes modules-api-ref.md from spellcheck

docs/reference/patterns/indexes.md
Fixed multi dimensional indexes miscalculation.
=> Fix multi dimensional indexes miscalculation

docs/data-types/_index.md, docs/data-types/bitfields.md, docs/data-types/bitmaps.md, docs/data-types/geospatial.md, docs/data-types/hashes.md, docs/data-types/hyperloglogs.md, docs/data-types/lists.md, docs/data-types/sets.md, docs/data-types/sorted-sets.md, docs/data-types/streams-tutorial.md, docs/data-types/streams.md, docs/data-types/strings.md
* Formatting, auto-link magic
* Minor (?) edits
* [NEW] bitfield
* Typos, grammer, syntax etc...
=> Edits to #2046

docs/data-types/bitfields.md
Fix typo in Introduction to Redis bitfields
=> Fix typo in Introduction to Redis bitfields

docs/getting-started/installation/install-redis-on-windows.md
"the" shouldn't be in that sentence
=> Fixed typo

docs/getting-started/installation/install-redis-on-linux.md, wordlist
=> Adds note about lsb-release

docs/data-types/streams.md
=> Fixes link to stream intro

docs/getting-started/installation/install-redis-on-windows.md
=> Fixes link to install on Linux

docs/data-types/hyperloglogs.md
fix https://github.com/redis/redis-doc/issues/2098
=> fix link in hyperLogLog page

docs/reference/command-arguments.md
ref: https://github.com/redis/redis/pull/11051/
=> Add display_text to COMMAND DOCS

docs/reference/optimization/benchmarks.md
=> [BUG FIX] Correct default benchmark datasize

docs/reference/command-tips.md
Fixes #1907, updates the topic description
=> [BUG FIX] Update command tip topic description

commands/xgroup-createconsumer.md
Fixes #2054, adds a note about data presence
=> [BUG FIX] Update XGROUP CREATECONSUMER about stream data presence 

docs/data-types/streams.md
=> fix broken link to Redis Streams Tutorial

libraries/typescript/github.com/redis/redis-om-node.json
Incorrect name for the library. (Python --> Node.js)
=> Correct docs

modules/community/github.com/tzongw/redis-timer.json
Hey, guys, I've created a module and would like to add to the community modules.😄
[redis-timer](https://github.com/tzongw/redis-timer)
=> Add redis-timer module

docs/about/trademark.md
=> Fix section 7 'notification'

commands/bitop.md
keep description in update with latest option in `bitop` command
=> keep description in update with latest option in bitop command

docs/manual/scaling.md
Adds a link to enterprise content in Scaling, reformats notes and section heads, fixes spelling and grammar issues
=> [UPDATE] Add a link to linear scaling on redis.com

commands/xgroup-create.md
Fixes #2125 plus other copyedits
=> [BUG FIX] Edit typo in XGROUP-CREATE

docs/manual/security/_index.md
Adds a link to the security course
=> [UPDATE] Add a link to RU330 from the security topic

docs/manual/persistence.md, wordlist
Adds links to enterprise persistence options/configuration
=> [UPDATE] Link from persistence topic to enterprise persistence options/configuration

docs/data-types/tutorial.md
tense change of the word "execute"
=> tense change of the word "execute"

commands/acl-setuser.md
=> [BUG FIX] Remove a typo and copyedit content

commands/dump.md
Fixes #2076, corrects example output
=> [BUG FIX] Correct DUMP command example

commands/setex.md
=> [BUG FIX] Add TTL as a See also command to SETEX

docs/management/security/acl.md, wordlist
ref: https://github.com/redis/redis/pull/11279/files#diff-c683e35ac8c539e4f6c402fc159fe0e57086e3e661dd9ac7e48cedaee2c79c14R945
=> Fix outdated ACL SETUSER reset actions

docs/management/security/acl.md
All output is based on the current 7.0.6 version.
=> Minor fixes in outdated acl doc

clients/nodejs/github.com/anchovycation/metronom.json
Metronom is user friendly Redis ORM based on [node-redis](https://github.com/redis/node-redis)
You can **save**, **read**, **update**, **filter**, **delete** and **bulk** operations JavaScript objects in Redis **without needing to know Redis commands**.
It is used effortlessly without installing any plugins like RedisJSON. The system works with Hashes. It shreds the objects and saves them as key strings in the hash, and while reading, they break it down again according to the given scheme and type conversion with TypeScript.
**Source Code**: [anchovycation/metronom](https://github.com/anchovycation/metronom)
**NPM Package**: [https://www.npmjs.com/package/metronom](https://www.npmjs.com/package/metronom)
=> metronom added to Node clients

commands/spublish.md
=> Fix SPUBLISH reply description

commands/xreadgroup.md
=> Fix XREADGROUP command error

docs/manual/programmability/lua-api.md
Hej there, first of all: thanks for the exhaustive docs on Redis!
Stumbled across those three things while reading into the scripting API and wanted to give back ❤️
=> Formatting and spelling fixes in Lua API

docs/data-types/tutorial.md
Should either read "elements in a sorted set" or "elements in sorted sets".
=> Fix small typo in tutorial.md

commands/linsert.md
=> Clarified that LINSERT will return 0 if the key does not exist

commands/info.md
=> Document Sentinel fields in INFO command

docs/getting-started/_index.md, docs/reference/modules/modules-api-ref.md
Closes [DXDOCS-292](https://redislabs.atlassian.net/browse/DXDOCS-292)
=> Fixes links and typos

libraries/php/github.com/RobiNN1/phpCacheAdmin.json
A universal web dashboard with support for various cache systems with nicer ui. Also it supports both phpredis and predis clients.
=> Add phpCacheAdmin

tool_types.json, tools/other/github.com/IBM/operator-for-redis-cluster.json, tools/other/github.com/oliver006/redis_exporter.json, tools/other/github.com/spotahome/redis-operator.json
=> Add tools category 'Other' with K8s related tools

commands/acl-log.md
Updating the doc for the changes made in [redis/redis#11477](https://github.com/redis/redis/pull/11477).
Added description for the ACL LOG fields.
=> Updating the ACL LOG doc in acl-log.md.

commands.json
To https://github.com/redis/redis/commit/07d187066a86a9a3124af740373bf5bf49e345ff
=> Generate commands.json

docs/reference/key-specs.md
Actually there are four listed in the bullets below this statement.
Fixes #2337
=> Fix minor text inconsistency in key-specs

clients/python/github.com/DriverX/aioredis-cluster.json
Mature and production ready client based on aioredis v1.x.x
=> add Python aioredis-cluster client

commands.json, commands/wait.md, commands/waitaof.md, wordlist
and update commands.json to latest
=> Add documentation for new WAITAOF command, and update commands.json

commands/client-no-touch.md, commands/reset.md
For PR: redis/redis#11483
Add doc for `CLIENT NO-TOUCH`.
Update `RESET` command.
=> Add CLIENT NO-TOUCH. Update RESET command.

commands.json
Bumps to match https://github.com/redis/redis/pull/11942
=> Updates commands.json

docs/clients/_index.md, resources/clients/index.md, wordlist
Updates clients quickstart and clients inventory descriptions
=> Updates clients quickstart and clients inventory descriptions

docs/clients/_index.md
=> Updates clients quickstart alias

docs/manual/pubsub.md
=> Adds delivery semantics clause to Pub/Sub

docs/management/admin.md
Adds links to existing documentation spots that provide additional explanation on the suggested kernel parameter changes.
=> Add context to kernel parameter changes

docs/reference/modules/modules-blocking-ops.md
Ref: https://github.com/redis/redis/pull/10527
=> Removes REDISMODULE_EXPERIMENTAL_API

commands/cluster-addslots.md, commands/cluster-addslotsrange.md
Complements complete commands, this also helps us render
the command hyperlinks.
=> Minor fixes in cluster-addslots / cluster-addslotsrange

docs/clients/go.md
ctx parameter is not yet initialized in the examples so I pass the context.Background()
=> Update context parameter in go.md

docs/clients/go.md
Wrapping the base example with a main, given the number of questions received on this.
=> Wrapping the base example with a main

commands.json, docs/reference/modules/modules-api-ref.md
includes some minor edits for commands.json arguments, and a few new module APIs
=> update commands.json and module docs with 7.2 RC2

commands/get.md, commands/set.md
Depends on shortcode introduced in https://github.com/redis-stack/redis-stack-website/pull/99
=> Add set&get code example

docs/data-types/tutorial.md
https://github.com/redis/redis-doc/blob/master/wordlist#L216
=> Update text leaderboard

docs/manual/programmability/lua-debugging.md
Get the latest message from unstable code, see redis/redis#2946
=> Update Lua debugging help message commands for consistency

commands/slowlog-get.md, commands/slowlog-len.md, commands/slowlog-reset.md, commands/xinfo-consumers.md, commands/xinfo-groups.md
=> Replace `@reply` with `@return`

docs/data-types/bitmaps.md
Fixed erroneous reference to "server" that should be "sensor".
=> Fixed typo in bitmaps page

docs/manual/pubsub.md
=> Edits Pub/Sub example

modules/community/github.com/t-fuchi/RedisMMap.json
Adding my [RedisMMap](https://github.com/t-fuchi/RedisMMap) module to the list.
=> Add RedisMMap to the community modules list

tools/gui/github.com/qishibo/AnotherRedisDesktopManager.json
Hey there 👋
Just want to list ARDM on the tools page and give users one more choice.
ARDM is open source on Github: https://github.com/qishibo/AnotherRedisDesktopManager
Thanks for all the great work you guys have been doing ❤️
=> Add ARDM to the tools page

docs/management/scaling.md
Found this small grammatical error while reading the docs
=> Change `don't` to `not` for grammar

docs/getting-started/_index.md, docs/management/scaling.md
Changes:
- Added Redis Cloud as option to main Get Started page per Tomer Zvirsh
- Changed Scaling title to Scale with Redis Cloud under Management
Closes #2533
=> Add RC as option in main get started page + minor title fix

docs/getting-started/_index.md, docs/getting-started/installation/install-redis-from-source.md
=> DOC-2755: update get started for clarity

commands/client-list.md
no-evict added in https://github.com/redis/redis/pull/8687
no-touch added in https://github.com/redis/redis/pull/11483
=> update client list fields: no-evict and no-touch

commands.json
see https://github.com/redis/redis/pull/12633
=> update commands spec (args) from 7.2.2

docs/reference/protocol-spec.md
Just a couple of typos I stumbled upon.
=> Fix typos in protocol-spec.md

docs/data-types/lists.md
=> Minor correction to list data type page

clients/gleam/github.com/massivefermion/radish.json, languages.json
[Radish](https://hex.pm/packages/radish) is the client for the [Gleam programming language](https://gleam.run/). It's newly published so there is still a lot of work to do.
Just one question, what should I do to get recommended? What are the criteria?
Thanks
=> added radish, the gleam client

commands/incr.md
fix a small grammatical mistake.
=> Change 'this' to 'these'.

commands/info.md
=> Add new pubsub_clients field in INFO

docs/reference/clients.md
Simplify/clarify and align with other config docs
=> Update `maxclients` directive in `redis.conf` info/wording

commands/memory-usage.md
Just a small fix in the grammar of this sentence.
=> Grammar fix - Add missing 'and'

libraries/c/github.com/redis/librdb.json, tools/other/github.com/redis/librdb.json
https://github.com/redis/librdb
=> Adding librdb as a new recommended tool and c-library

docs/install/install-redis/_index.md
While I was scrolling through the docs I noticed a broken link. Fixed it here.
=> Bugfix-install redis broken link

commands/client-kill.md
Add documentation for https://github.com/redis/redis/pull/12299/
=> Document CLIENT KILL MAXAGE filter
